// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file sunrise/liquidityincentive/gauge.proto (package sunrise.liquidityincentive, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_amino_amino } from "../../amino/amino_pb";
import { file_cosmos_proto_cosmos } from "../../cosmos_proto/cosmos_pb";
import { file_gogoproto_gogo } from "../../gogoproto/gogo_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file sunrise/liquidityincentive/gauge.proto.
 */
export const file_sunrise_liquidityincentive_gauge: GenFile = /*@__PURE__*/
  fileDesc("CiZzdW5yaXNlL2xpcXVpZGl0eWluY2VudGl2ZS9nYXVnZS5wcm90bxIac3VucmlzZS5saXF1aWRpdHlpbmNlbnRpdmUidQoFR2F1Z2USGQoRcHJldmlvdXNfZXBvY2hfaWQYASABKAQSDwoHcG9vbF9pZBgCIAEoBBJACgVyYXRpbxgDIAEoCUIxyN4fANreHxtjb3Ntb3NzZGsuaW8vbWF0aC5MZWdhY3lEZWPStC0KY29zbW9zLkRlYyJgCgpQb29sV2VpZ2h0Eg8KB3Bvb2xfaWQYASABKAQSQQoGd2VpZ2h0GAIgASgJQjHI3h8A2t4fG2Nvc21vc3Nkay5pby9tYXRoLkxlZ2FjeURlY9K0LQpjb3Ntb3MuRGVjIlUKBFZvdGUSDgoGc2VuZGVyGAEgASgJEj0KB3dlaWdodHMYAiADKAsyJi5zdW5yaXNlLmxpcXVpZGl0eWluY2VudGl2ZS5Qb29sV2VpZ2h0QgTI3h8AQvEBCh5jb20uc3VucmlzZS5saXF1aWRpdHlpbmNlbnRpdmVCCkdhdWdlUHJvdG9QAVo6Z2l0aHViLmNvbS9zdW5yaXNlbGF5ZXIvc3VucmlzZS94L2xpcXVpZGl0eWluY2VudGl2ZS90eXBlc6ICA1NMWKoCGlN1bnJpc2UuTGlxdWlkaXR5aW5jZW50aXZlygIaU3VucmlzZVxMaXF1aWRpdHlpbmNlbnRpdmXiAiZTdW5yaXNlXExpcXVpZGl0eWluY2VudGl2ZVxHUEJNZXRhZGF0YeoCG1N1bnJpc2U6OkxpcXVpZGl0eWluY2VudGl2ZWIGcHJvdG8z", [file_amino_amino, file_cosmos_proto_cosmos, file_gogoproto_gogo]);

/**
 * @generated from message sunrise.liquidityincentive.Gauge
 */
export type Gauge = Message<"sunrise.liquidityincentive.Gauge"> & {
  /**
   * @generated from field: uint64 previous_epoch_id = 1;
   */
  previousEpochId: bigint;

  /**
   * @generated from field: uint64 pool_id = 2;
   */
  poolId: bigint;

  /**
   * @generated from field: string ratio = 3;
   */
  ratio: string;
};

/**
 * Describes the message sunrise.liquidityincentive.Gauge.
 * Use `create(GaugeSchema)` to create a new message.
 */
export const GaugeSchema: GenMessage<Gauge> = /*@__PURE__*/
  messageDesc(file_sunrise_liquidityincentive_gauge, 0);

/**
 * @generated from message sunrise.liquidityincentive.PoolWeight
 */
export type PoolWeight = Message<"sunrise.liquidityincentive.PoolWeight"> & {
  /**
   * @generated from field: uint64 pool_id = 1;
   */
  poolId: bigint;

  /**
   * @generated from field: string weight = 2;
   */
  weight: string;
};

/**
 * Describes the message sunrise.liquidityincentive.PoolWeight.
 * Use `create(PoolWeightSchema)` to create a new message.
 */
export const PoolWeightSchema: GenMessage<PoolWeight> = /*@__PURE__*/
  messageDesc(file_sunrise_liquidityincentive_gauge, 1);

/**
 * @generated from message sunrise.liquidityincentive.Vote
 */
export type Vote = Message<"sunrise.liquidityincentive.Vote"> & {
  /**
   * @generated from field: string sender = 1;
   */
  sender: string;

  /**
   * @generated from field: repeated sunrise.liquidityincentive.PoolWeight weights = 2;
   */
  weights: PoolWeight[];
};

/**
 * Describes the message sunrise.liquidityincentive.Vote.
 * Use `create(VoteSchema)` to create a new message.
 */
export const VoteSchema: GenMessage<Vote> = /*@__PURE__*/
  messageDesc(file_sunrise_liquidityincentive_gauge, 2);

