// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file sunrise/liquidityincentive/params.proto (package sunrise.liquidityincentive, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_amino_amino } from "../../amino/amino_pb";
import { file_gogoproto_gogo } from "../../gogoproto/gogo_pb";
import { file_cosmos_proto_cosmos } from "../../cosmos_proto/cosmos_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file sunrise/liquidityincentive/params.proto.
 */
export const file_sunrise_liquidityincentive_params: GenFile = /*@__PURE__*/
  fileDesc("CidzdW5yaXNlL2xpcXVpZGl0eWluY2VudGl2ZS9wYXJhbXMucHJvdG8SGnN1bnJpc2UubGlxdWlkaXR5aW5jZW50aXZlIp0BCgZQYXJhbXMSFAoMZXBvY2hfYmxvY2tzGAEgASgDEk8KFHN0YWtpbmdfcmV3YXJkX3JhdGlvGAIgASgJQjHI3h8A2t4fG2Nvc21vc3Nkay5pby9tYXRoLkxlZ2FjeURlY9K0LQpjb3Ntb3MuRGVjOizooB8BiuewKiNzdW5yaXNlL3gvbGlxdWlkaXR5aW5jZW50aXZlL1BhcmFtc0LyAQoeY29tLnN1bnJpc2UubGlxdWlkaXR5aW5jZW50aXZlQgtQYXJhbXNQcm90b1ABWjpnaXRodWIuY29tL3N1bnJpc2VsYXllci9zdW5yaXNlL3gvbGlxdWlkaXR5aW5jZW50aXZlL3R5cGVzogIDU0xYqgIaU3VucmlzZS5MaXF1aWRpdHlpbmNlbnRpdmXKAhpTdW5yaXNlXExpcXVpZGl0eWluY2VudGl2ZeICJlN1bnJpc2VcTGlxdWlkaXR5aW5jZW50aXZlXEdQQk1ldGFkYXRh6gIbU3VucmlzZTo6TGlxdWlkaXR5aW5jZW50aXZlYgZwcm90bzM", [file_amino_amino, file_gogoproto_gogo, file_cosmos_proto_cosmos]);

/**
 * Params defines the parameters for the module.
 *
 * @generated from message sunrise.liquidityincentive.Params
 */
export type Params = Message<"sunrise.liquidityincentive.Params"> & {
  /**
   * @generated from field: int64 epoch_blocks = 1;
   */
  epochBlocks: bigint;

  /**
   * @generated from field: string staking_reward_ratio = 2;
   */
  stakingRewardRatio: string;
};

/**
 * Describes the message sunrise.liquidityincentive.Params.
 * Use `create(ParamsSchema)` to create a new message.
 */
export const ParamsSchema: GenMessage<Params> = /*@__PURE__*/
  messageDesc(file_sunrise_liquidityincentive_params, 0);

