// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file sunrise/liquidityincentive/params.proto (package sunrise.liquidityincentive, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_cosmos_proto_cosmos } from "../../cosmos_proto/cosmos_pb";
import { file_gogoproto_gogo } from "../../gogoproto/gogo_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file sunrise/liquidityincentive/params.proto.
 */
export const file_sunrise_liquidityincentive_params: GenFile = /*@__PURE__*/
  fileDesc("CidzdW5yaXNlL2xpcXVpZGl0eWluY2VudGl2ZS9wYXJhbXMucHJvdG8SGnN1bnJpc2UubGlxdWlkaXR5aW5jZW50aXZlInUKBlBhcmFtcxIUCgxlcG9jaF9ibG9ja3MYASABKAMSTwoUc3Rha2luZ19yZXdhcmRfcmF0aW8YAiABKAlCMcjeHwDa3h8bY29zbW9zc2RrLmlvL21hdGguTGVnYWN5RGVj0rQtCmNvc21vcy5EZWM6BOigHwFC8gEKHmNvbS5zdW5yaXNlLmxpcXVpZGl0eWluY2VudGl2ZUILUGFyYW1zUHJvdG9QAVo6Z2l0aHViLmNvbS9zdW5yaXNlbGF5ZXIvc3VucmlzZS94L2xpcXVpZGl0eWluY2VudGl2ZS90eXBlc6ICA1NMWKoCGlN1bnJpc2UuTGlxdWlkaXR5aW5jZW50aXZlygIaU3VucmlzZVxMaXF1aWRpdHlpbmNlbnRpdmXiAiZTdW5yaXNlXExpcXVpZGl0eWluY2VudGl2ZVxHUEJNZXRhZGF0YeoCG1N1bnJpc2U6OkxpcXVpZGl0eWluY2VudGl2ZWIGcHJvdG8z", [file_cosmos_proto_cosmos, file_gogoproto_gogo]);

/**
 * Params defines the parameters for the module.
 *
 * @generated from message sunrise.liquidityincentive.Params
 */
export type Params = Message<"sunrise.liquidityincentive.Params"> & {
  /**
   * @generated from field: int64 epoch_blocks = 1;
   */
  epochBlocks: bigint;

  /**
   * @generated from field: string staking_reward_ratio = 2;
   */
  stakingRewardRatio: string;
};

/**
 * Describes the message sunrise.liquidityincentive.Params.
 * Use `create(ParamsSchema)` to create a new message.
 */
export const ParamsSchema: GenMessage<Params> = /*@__PURE__*/
  messageDesc(file_sunrise_liquidityincentive_params, 0);

