// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file sunrise/da/v1/published_data.proto (package sunrise.da.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Coin } from "../../../cosmos/base/v1beta1/coin_pb";
import { file_cosmos_base_v1beta1_coin } from "../../../cosmos/base/v1beta1/coin_pb";
import { file_gogoproto_gogo } from "../../../gogoproto/gogo_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file sunrise/da/v1/published_data.proto.
 */
export const file_sunrise_da_v1_published_data: GenFile = /*@__PURE__*/
  fileDesc("CiJzdW5yaXNlL2RhL3YxL3B1Ymxpc2hlZF9kYXRhLnByb3RvEg1zdW5yaXNlLmRhLnYxIqMECg1QdWJsaXNoZWREYXRhEhQKDG1ldGFkYXRhX3VyaRgBIAEoCRIaChJwYXJpdHlfc2hhcmRfY291bnQYAiABKAQSGwoTc2hhcmRfZG91YmxlX2hhc2hlcxgDIAMoDBI3Cgl0aW1lc3RhbXAYBCABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wQgjI3h8AkN8fARIlCgZzdGF0dXMYBSABKA4yFS5zdW5yaXNlLmRhLnYxLlN0YXR1cxIRCglwdWJsaXNoZXIYBiABKAkSEgoKY2hhbGxlbmdlchgHIAEoCRJsChdwdWJsaXNoX2RhdGFfY29sbGF0ZXJhbBgIIAMoCzIZLmNvc21vcy5iYXNlLnYxYmV0YTEuQ29pbkIwyN4fAKrfHyhnaXRodWIuY29tL2Nvc21vcy9jb3Ntb3Mtc2RrL3R5cGVzLkNvaW5zEnEKHHN1Ym1pdF9pbnZhbGlkaXR5X2NvbGxhdGVyYWwYCSADKAsyGS5jb3Ntb3MuYmFzZS52MWJldGExLkNvaW5CMMjeHwCq3x8oZ2l0aHViLmNvbS9jb3Ntb3MvY29zbW9zLXNkay90eXBlcy5Db2lucxJBChNjaGFsbGVuZ2VfdGltZXN0YW1wGAogASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEIIyN4fAJDfHwESGAoQZGF0YV9zb3VyY2VfaW5mbxgLIAEoCSJOCgVQcm9vZhIUCgxtZXRhZGF0YV91cmkYASABKAkSDgoGc2VuZGVyGAIgASgJEg8KB2luZGljZXMYAyADKAMSDgoGcHJvb2ZzGAQgAygMIkMKCkludmFsaWRpdHkSFAoMbWV0YWRhdGFfdXJpGAEgASgJEg4KBnNlbmRlchgCIAEoCRIPCgdpbmRpY2VzGAMgAygDKn8KBlN0YXR1cxIWChJTVEFUVVNfVU5TUEVDSUZJRUQQABITCg9TVEFUVVNfVkVSSUZJRUQQARITCg9TVEFUVVNfUkVKRUNURUQQAhIbChdTVEFUVVNfQ0hBTExFTkdFX1BFUklPRBADEhYKElNUQVRVU19DSEFMTEVOR0lORxAEQqkBChFjb20uc3VucmlzZS5kYS52MUISUHVibGlzaGVkRGF0YVByb3RvUAFaKmdpdGh1Yi5jb20vc3VucmlzZWxheWVyL3N1bnJpc2UveC9kYS90eXBlc6ICA1NEWKoCDVN1bnJpc2UuRGEuVjHKAg1TdW5yaXNlXERhXFYx4gIZU3VucmlzZVxEYVxWMVxHUEJNZXRhZGF0YeoCD1N1bnJpc2U6OkRhOjpWMWIGcHJvdG8z", [file_cosmos_base_v1beta1_coin, file_gogoproto_gogo, file_google_protobuf_timestamp]);

/**
 * PublishedData
 *
 * @generated from message sunrise.da.v1.PublishedData
 */
export type PublishedData = Message<"sunrise.da.v1.PublishedData"> & {
  /**
   * @generated from field: string metadata_uri = 1;
   */
  metadataUri: string;

  /**
   * @generated from field: uint64 parity_shard_count = 2;
   */
  parityShardCount: bigint;

  /**
   * @generated from field: repeated bytes shard_double_hashes = 3;
   */
  shardDoubleHashes: Uint8Array[];

  /**
   * @generated from field: google.protobuf.Timestamp timestamp = 4;
   */
  timestamp?: Timestamp;

  /**
   * @generated from field: sunrise.da.v1.Status status = 5;
   */
  status: Status;

  /**
   * @generated from field: string publisher = 6;
   */
  publisher: string;

  /**
   * @generated from field: string challenger = 7;
   */
  challenger: string;

  /**
   * @generated from field: repeated cosmos.base.v1beta1.Coin publish_data_collateral = 8;
   */
  publishDataCollateral: Coin[];

  /**
   * @generated from field: repeated cosmos.base.v1beta1.Coin submit_invalidity_collateral = 9;
   */
  submitInvalidityCollateral: Coin[];

  /**
   * @generated from field: google.protobuf.Timestamp challenge_timestamp = 10;
   */
  challengeTimestamp?: Timestamp;

  /**
   * @generated from field: string data_source_info = 11;
   */
  dataSourceInfo: string;
};

/**
 * Describes the message sunrise.da.v1.PublishedData.
 * Use `create(PublishedDataSchema)` to create a new message.
 */
export const PublishedDataSchema: GenMessage<PublishedData> = /*@__PURE__*/
  messageDesc(file_sunrise_da_v1_published_data, 0);

/**
 * Proof
 *
 * @generated from message sunrise.da.v1.Proof
 */
export type Proof = Message<"sunrise.da.v1.Proof"> & {
  /**
   * @generated from field: string metadata_uri = 1;
   */
  metadataUri: string;

  /**
   * @generated from field: string sender = 2;
   */
  sender: string;

  /**
   * @generated from field: repeated int64 indices = 3;
   */
  indices: bigint[];

  /**
   * @generated from field: repeated bytes proofs = 4;
   */
  proofs: Uint8Array[];
};

/**
 * Describes the message sunrise.da.v1.Proof.
 * Use `create(ProofSchema)` to create a new message.
 */
export const ProofSchema: GenMessage<Proof> = /*@__PURE__*/
  messageDesc(file_sunrise_da_v1_published_data, 1);

/**
 * Invalidity
 *
 * @generated from message sunrise.da.v1.Invalidity
 */
export type Invalidity = Message<"sunrise.da.v1.Invalidity"> & {
  /**
   * @generated from field: string metadata_uri = 1;
   */
  metadataUri: string;

  /**
   * @generated from field: string sender = 2;
   */
  sender: string;

  /**
   * @generated from field: repeated int64 indices = 3;
   */
  indices: bigint[];
};

/**
 * Describes the message sunrise.da.v1.Invalidity.
 * Use `create(InvaliditySchema)` to create a new message.
 */
export const InvaliditySchema: GenMessage<Invalidity> = /*@__PURE__*/
  messageDesc(file_sunrise_da_v1_published_data, 2);

/**
 * PublishedDataStatus
 *
 * @generated from enum sunrise.da.v1.Status
 */
export enum Status {
  /**
   * Default value
   *
   * @generated from enum value: STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Verified
   *
   * @generated from enum value: STATUS_VERIFIED = 1;
   */
  VERIFIED = 1,

  /**
   * Rejected
   *
   * @generated from enum value: STATUS_REJECTED = 2;
   */
  REJECTED = 2,

  /**
   * Verified the votes from the validators. Challenge can be received (after preBlocker)
   *
   * @generated from enum value: STATUS_CHALLENGE_PERIOD = 3;
   */
  CHALLENGE_PERIOD = 3,

  /**
   * A certain number of SubmitInvalidity received. Validators can send SubmitValidityProof tx.
   *
   * @generated from enum value: STATUS_CHALLENGING = 4;
   */
  CHALLENGING = 4,
}

/**
 * Describes the enum sunrise.da.v1.Status.
 */
export const StatusSchema: GenEnum<Status> = /*@__PURE__*/
  enumDesc(file_sunrise_da_v1_published_data, 0);

