// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file sunrise/liquiditypool/v1/params.proto (package sunrise.liquiditypool.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_cosmos_proto_cosmos } from "../../../cosmos_proto/cosmos_pb";
import { file_gogoproto_gogo } from "../../../gogoproto/gogo_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file sunrise/liquiditypool/v1/params.proto.
 */
export const file_sunrise_liquiditypool_v1_params: GenFile = /*@__PURE__*/
  fileDesc("CiVzdW5yaXNlL2xpcXVpZGl0eXBvb2wvdjEvcGFyYW1zLnByb3RvEhhzdW5yaXNlLmxpcXVpZGl0eXBvb2wudjEiaQoGUGFyYW1zEikKEXdpdGhkcmF3X2ZlZV9yYXRlGAEgASgJQg7StC0KY29zbW9zLkRlYxIuChZzd2FwX3RyZWFzdXJ5X3RheF9yYXRlGAIgASgJQg7StC0KY29zbW9zLkRlYzoE6KAfAULkAQocY29tLnN1bnJpc2UubGlxdWlkaXR5cG9vbC52MUILUGFyYW1zUHJvdG9QAVo1Z2l0aHViLmNvbS9zdW5yaXNlbGF5ZXIvc3VucmlzZS94L2xpcXVpZGl0eXBvb2wvdHlwZXOiAgNTTFiqAhhTdW5yaXNlLkxpcXVpZGl0eXBvb2wuVjHKAhhTdW5yaXNlXExpcXVpZGl0eXBvb2xcVjHiAiRTdW5yaXNlXExpcXVpZGl0eXBvb2xcVjFcR1BCTWV0YWRhdGHqAhpTdW5yaXNlOjpMaXF1aWRpdHlwb29sOjpWMWIGcHJvdG8z", [file_cosmos_proto_cosmos, file_gogoproto_gogo]);

/**
 * Params defines the parameters for the module.
 *
 * @generated from message sunrise.liquiditypool.v1.Params
 */
export type Params = Message<"sunrise.liquiditypool.v1.Params"> & {
  /**
   * For reservation, not used yet
   *
   * @generated from field: string withdraw_fee_rate = 1;
   */
  withdrawFeeRate: string;

  /**
   * For reservation, not used yet
   *
   * @generated from field: string swap_treasury_tax_rate = 2;
   */
  swapTreasuryTaxRate: string;
};

/**
 * Describes the message sunrise.liquiditypool.v1.Params.
 * Use `create(ParamsSchema)` to create a new message.
 */
export const ParamsSchema: GenMessage<Params> = /*@__PURE__*/
  messageDesc(file_sunrise_liquiditypool_v1_params, 0);

