// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file sunrise/swap/v1/in_flight_packet.proto (package sunrise.swap.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_cosmos_proto_cosmos } from "../../../cosmos_proto/cosmos_pb";
import { file_gogoproto_gogo } from "../../../gogoproto/gogo_pb";
import type { RouteResult } from "./route_pb";
import { file_sunrise_swap_v1_route } from "./route_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file sunrise/swap/v1/in_flight_packet.proto.
 */
export const file_sunrise_swap_v1_in_flight_packet: GenFile = /*@__PURE__*/
  fileDesc("CiZzdW5yaXNlL3N3YXAvdjEvaW5fZmxpZ2h0X3BhY2tldC5wcm90bxIPc3VucmlzZS5zd2FwLnYxIkQKC1BhY2tldEluZGV4Eg8KB3BvcnRfaWQYASABKAkSEgoKY2hhbm5lbF9pZBgCIAEoCRIQCghzZXF1ZW5jZRgDIAEoBCL/AwoWSW5jb21pbmdJbkZsaWdodFBhY2tldBIxCgVpbmRleBgBIAEoCzIcLnN1bnJpc2Uuc3dhcC52MS5QYWNrZXRJbmRleEIEyN4fABIMCgRkYXRhGAIgASgMEhMKC3NyY19wb3J0X2lkGAMgASgJEhYKDnNyY19jaGFubmVsX2lkGAQgASgJEhYKDnRpbWVvdXRfaGVpZ2h0GAUgASgJEhkKEXRpbWVvdXRfdGltZXN0YW1wGAYgASgEEgsKA2FjaxgHIAEoDBIyCgZyZXN1bHQYCCABKAsyHC5zdW5yaXNlLnN3YXAudjEuUm91dGVSZXN1bHRCBMjeHwASQgoNaW50ZXJmYWNlX2ZlZRgJIAEoCUIryN4fANreHxVjb3Ntb3NzZGsuaW8vbWF0aC5JbnTStC0KY29zbW9zLkludBI9ChVvdXRnb2luZ19pbmRleF9jaGFuZ2UYCiABKAsyHC5zdW5yaXNlLnN3YXAudjEuUGFja2V0SW5kZXhIABIUCgphY2tfY2hhbmdlGAsgASgMSAASPgoWb3V0Z29pbmdfaW5kZXhfZm9yd2FyZBgMIAEoCzIcLnN1bnJpc2Uuc3dhcC52MS5QYWNrZXRJbmRleEgBEhUKC2Fja19mb3J3YXJkGA0gASgMSAFCCAoGY2hhbmdlQgkKB2ZvcndhcmQipQEKFk91dGdvaW5nSW5GbGlnaHRQYWNrZXQSMQoFaW5kZXgYASABKAsyHC5zdW5yaXNlLnN3YXAudjEuUGFja2V0SW5kZXhCBMjeHwASPQoRYWNrX3dhaXRpbmdfaW5kZXgYAiABKAsyHC5zdW5yaXNlLnN3YXAudjEuUGFja2V0SW5kZXhCBMjeHwASGQoRcmV0cmllc19yZW1haW5pbmcYAyABKAVCtgEKE2NvbS5zdW5yaXNlLnN3YXAudjFCE0luRmxpZ2h0UGFja2V0UHJvdG9QAVosZ2l0aHViLmNvbS9zdW5yaXNlbGF5ZXIvc3VucmlzZS94L3N3YXAvdHlwZXOiAgNTU1iqAg9TdW5yaXNlLlN3YXAuVjHKAg9TdW5yaXNlXFN3YXBcVjHiAhtTdW5yaXNlXFN3YXBcVjFcR1BCTWV0YWRhdGHqAhFTdW5yaXNlOjpTd2FwOjpWMWIGcHJvdG8z", [file_cosmos_proto_cosmos, file_gogoproto_gogo, file_sunrise_swap_v1_route]);

/**
 * PacketIndex
 *
 * @generated from message sunrise.swap.v1.PacketIndex
 */
export type PacketIndex = Message<"sunrise.swap.v1.PacketIndex"> & {
  /**
   * @generated from field: string port_id = 1;
   */
  portId: string;

  /**
   * @generated from field: string channel_id = 2;
   */
  channelId: string;

  /**
   * @generated from field: uint64 sequence = 3;
   */
  sequence: bigint;
};

/**
 * Describes the message sunrise.swap.v1.PacketIndex.
 * Use `create(PacketIndexSchema)` to create a new message.
 */
export const PacketIndexSchema: GenMessage<PacketIndex> = /*@__PURE__*/
  messageDesc(file_sunrise_swap_v1_in_flight_packet, 0);

/**
 * IncomingInFlightPacket
 *
 * @generated from message sunrise.swap.v1.IncomingInFlightPacket
 */
export type IncomingInFlightPacket = Message<"sunrise.swap.v1.IncomingInFlightPacket"> & {
  /**
   * @generated from field: sunrise.swap.v1.PacketIndex index = 1;
   */
  index?: PacketIndex;

  /**
   * @generated from field: bytes data = 2;
   */
  data: Uint8Array;

  /**
   * @generated from field: string src_port_id = 3;
   */
  srcPortId: string;

  /**
   * @generated from field: string src_channel_id = 4;
   */
  srcChannelId: string;

  /**
   * @generated from field: string timeout_height = 5;
   */
  timeoutHeight: string;

  /**
   * @generated from field: uint64 timeout_timestamp = 6;
   */
  timeoutTimestamp: bigint;

  /**
   * @generated from field: bytes ack = 7;
   */
  ack: Uint8Array;

  /**
   * @generated from field: sunrise.swap.v1.RouteResult result = 8;
   */
  result?: RouteResult;

  /**
   * @generated from field: string interface_fee = 9;
   */
  interfaceFee: string;

  /**
   * change
   *
   * @generated from oneof sunrise.swap.v1.IncomingInFlightPacket.change
   */
  change: {
    /**
     * @generated from field: sunrise.swap.v1.PacketIndex outgoing_index_change = 10;
     */
    value: PacketIndex;
    case: "outgoingIndexChange";
  } | {
    /**
     * @generated from field: bytes ack_change = 11;
     */
    value: Uint8Array;
    case: "ackChange";
  } | { case: undefined; value?: undefined };

  /**
   * forward
   *
   * @generated from oneof sunrise.swap.v1.IncomingInFlightPacket.forward
   */
  forward: {
    /**
     * @generated from field: sunrise.swap.v1.PacketIndex outgoing_index_forward = 12;
     */
    value: PacketIndex;
    case: "outgoingIndexForward";
  } | {
    /**
     * @generated from field: bytes ack_forward = 13;
     */
    value: Uint8Array;
    case: "ackForward";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message sunrise.swap.v1.IncomingInFlightPacket.
 * Use `create(IncomingInFlightPacketSchema)` to create a new message.
 */
export const IncomingInFlightPacketSchema: GenMessage<IncomingInFlightPacket> = /*@__PURE__*/
  messageDesc(file_sunrise_swap_v1_in_flight_packet, 1);

/**
 * OutgoingInFlightPacket
 *
 * @generated from message sunrise.swap.v1.OutgoingInFlightPacket
 */
export type OutgoingInFlightPacket = Message<"sunrise.swap.v1.OutgoingInFlightPacket"> & {
  /**
   * @generated from field: sunrise.swap.v1.PacketIndex index = 1;
   */
  index?: PacketIndex;

  /**
   * @generated from field: sunrise.swap.v1.PacketIndex ack_waiting_index = 2;
   */
  ackWaitingIndex?: PacketIndex;

  /**
   * @generated from field: int32 retries_remaining = 3;
   */
  retriesRemaining: number;
};

/**
 * Describes the message sunrise.swap.v1.OutgoingInFlightPacket.
 * Use `create(OutgoingInFlightPacketSchema)` to create a new message.
 */
export const OutgoingInFlightPacketSchema: GenMessage<OutgoingInFlightPacket> = /*@__PURE__*/
  messageDesc(file_sunrise_swap_v1_in_flight_packet, 2);

