// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file sunrise/swap/v1/route.proto (package sunrise.swap.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_amino_amino } from "../../../amino/amino_pb";
import type { Coin } from "../../../cosmos/base/v1beta1/coin_pb";
import { file_cosmos_base_v1beta1_coin } from "../../../cosmos/base/v1beta1/coin_pb";
import { file_cosmos_proto_cosmos } from "../../../cosmos_proto/cosmos_pb";
import { file_gogoproto_gogo } from "../../../gogoproto/gogo_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file sunrise/swap/v1/route.proto.
 */
export const file_sunrise_swap_v1_route: GenFile = /*@__PURE__*/
  fileDesc("ChtzdW5yaXNlL3N3YXAvdjEvcm91dGUucHJvdG8SD3N1bnJpc2Uuc3dhcC52MSIjCglSb3V0ZVBvb2wSFgoHcG9vbF9pZBgBIAEoBEIFqOewKgEiOwoLUm91dGVTZXJpZXMSLAoGcm91dGVzGAEgAygLMhYuc3VucmlzZS5zd2FwLnYxLlJvdXRlQgTI3h8AIl4KDVJvdXRlUGFyYWxsZWwSLAoGcm91dGVzGAEgAygLMhYuc3VucmlzZS5zd2FwLnYxLlJvdXRlQgTI3h8AEh8KB3dlaWdodHMYAiADKAlCDtK0LQpjb3Ntb3MuRGVjIsgBCgVSb3V0ZRIQCghkZW5vbV9pbhgBIAEoCRIRCglkZW5vbV9vdXQYAiABKAkSKgoEcG9vbBgDIAEoCzIaLnN1bnJpc2Uuc3dhcC52MS5Sb3V0ZVBvb2xIABIuCgZzZXJpZXMYBCABKAsyHC5zdW5yaXNlLnN3YXAudjEuUm91dGVTZXJpZXNIABIyCghwYXJhbGxlbBgFIAEoCzIeLnN1bnJpc2Uuc3dhcC52MS5Sb3V0ZVBhcmFsbGVsSABCCgoIc3RyYXRlZ3kiKQoPUm91dGVSZXN1bHRQb29sEhYKB3Bvb2xfaWQYASABKARCBajnsCoBIk4KEVJvdXRlUmVzdWx0U2VyaWVzEjkKDXJvdXRlX3Jlc3VsdHMYASADKAsyHC5zdW5yaXNlLnN3YXAudjEuUm91dGVSZXN1bHRCBMjeHwAiUAoTUm91dGVSZXN1bHRQYXJhbGxlbBI5Cg1yb3V0ZV9yZXN1bHRzGAEgAygLMhwuc3VucmlzZS5zd2FwLnYxLlJvdXRlUmVzdWx0QgTI3h8AIqICCgtSb3V0ZVJlc3VsdBIxCgh0b2tlbl9pbhgBIAEoCzIZLmNvc21vcy5iYXNlLnYxYmV0YTEuQ29pbkIEyN4fABIyCgl0b2tlbl9vdXQYAiABKAsyGS5jb3Ntb3MuYmFzZS52MWJldGExLkNvaW5CBMjeHwASMAoEcG9vbBgDIAEoCzIgLnN1bnJpc2Uuc3dhcC52MS5Sb3V0ZVJlc3VsdFBvb2xIABI0CgZzZXJpZXMYBCABKAsyIi5zdW5yaXNlLnN3YXAudjEuUm91dGVSZXN1bHRTZXJpZXNIABI4CghwYXJhbGxlbBgFIAEoCzIkLnN1bnJpc2Uuc3dhcC52MS5Sb3V0ZVJlc3VsdFBhcmFsbGVsSABCCgoIc3RyYXRlZ3lCrQEKE2NvbS5zdW5yaXNlLnN3YXAudjFCClJvdXRlUHJvdG9QAVosZ2l0aHViLmNvbS9zdW5yaXNlbGF5ZXIvc3VucmlzZS94L3N3YXAvdHlwZXOiAgNTU1iqAg9TdW5yaXNlLlN3YXAuVjHKAg9TdW5yaXNlXFN3YXBcVjHiAhtTdW5yaXNlXFN3YXBcVjFcR1BCTWV0YWRhdGHqAhFTdW5yaXNlOjpTd2FwOjpWMWIGcHJvdG8z", [file_amino_amino, file_cosmos_base_v1beta1_coin, file_cosmos_proto_cosmos, file_gogoproto_gogo]);

/**
 * RoutePool
 *
 * @generated from message sunrise.swap.v1.RoutePool
 */
export type RoutePool = Message<"sunrise.swap.v1.RoutePool"> & {
  /**
   * @generated from field: uint64 pool_id = 1;
   */
  poolId: bigint;
};

/**
 * Describes the message sunrise.swap.v1.RoutePool.
 * Use `create(RoutePoolSchema)` to create a new message.
 */
export const RoutePoolSchema: GenMessage<RoutePool> = /*@__PURE__*/
  messageDesc(file_sunrise_swap_v1_route, 0);

/**
 * RouteSeries
 *
 * @generated from message sunrise.swap.v1.RouteSeries
 */
export type RouteSeries = Message<"sunrise.swap.v1.RouteSeries"> & {
  /**
   * @generated from field: repeated sunrise.swap.v1.Route routes = 1;
   */
  routes: Route[];
};

/**
 * Describes the message sunrise.swap.v1.RouteSeries.
 * Use `create(RouteSeriesSchema)` to create a new message.
 */
export const RouteSeriesSchema: GenMessage<RouteSeries> = /*@__PURE__*/
  messageDesc(file_sunrise_swap_v1_route, 1);

/**
 * RouteParallel
 *
 * @generated from message sunrise.swap.v1.RouteParallel
 */
export type RouteParallel = Message<"sunrise.swap.v1.RouteParallel"> & {
  /**
   * @generated from field: repeated sunrise.swap.v1.Route routes = 1;
   */
  routes: Route[];

  /**
   * @generated from field: repeated string weights = 2;
   */
  weights: string[];
};

/**
 * Describes the message sunrise.swap.v1.RouteParallel.
 * Use `create(RouteParallelSchema)` to create a new message.
 */
export const RouteParallelSchema: GenMessage<RouteParallel> = /*@__PURE__*/
  messageDesc(file_sunrise_swap_v1_route, 2);

/**
 * Route
 *
 * @generated from message sunrise.swap.v1.Route
 */
export type Route = Message<"sunrise.swap.v1.Route"> & {
  /**
   * @generated from field: string denom_in = 1;
   */
  denomIn: string;

  /**
   * @generated from field: string denom_out = 2;
   */
  denomOut: string;

  /**
   * strategy
   *
   * @generated from oneof sunrise.swap.v1.Route.strategy
   */
  strategy: {
    /**
     * @generated from field: sunrise.swap.v1.RoutePool pool = 3;
     */
    value: RoutePool;
    case: "pool";
  } | {
    /**
     * @generated from field: sunrise.swap.v1.RouteSeries series = 4;
     */
    value: RouteSeries;
    case: "series";
  } | {
    /**
     * @generated from field: sunrise.swap.v1.RouteParallel parallel = 5;
     */
    value: RouteParallel;
    case: "parallel";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message sunrise.swap.v1.Route.
 * Use `create(RouteSchema)` to create a new message.
 */
export const RouteSchema: GenMessage<Route> = /*@__PURE__*/
  messageDesc(file_sunrise_swap_v1_route, 3);

/**
 * RouteResultPool
 *
 * @generated from message sunrise.swap.v1.RouteResultPool
 */
export type RouteResultPool = Message<"sunrise.swap.v1.RouteResultPool"> & {
  /**
   * @generated from field: uint64 pool_id = 1;
   */
  poolId: bigint;
};

/**
 * Describes the message sunrise.swap.v1.RouteResultPool.
 * Use `create(RouteResultPoolSchema)` to create a new message.
 */
export const RouteResultPoolSchema: GenMessage<RouteResultPool> = /*@__PURE__*/
  messageDesc(file_sunrise_swap_v1_route, 4);

/**
 * RouteResultSeries
 *
 * @generated from message sunrise.swap.v1.RouteResultSeries
 */
export type RouteResultSeries = Message<"sunrise.swap.v1.RouteResultSeries"> & {
  /**
   * @generated from field: repeated sunrise.swap.v1.RouteResult route_results = 1;
   */
  routeResults: RouteResult[];
};

/**
 * Describes the message sunrise.swap.v1.RouteResultSeries.
 * Use `create(RouteResultSeriesSchema)` to create a new message.
 */
export const RouteResultSeriesSchema: GenMessage<RouteResultSeries> = /*@__PURE__*/
  messageDesc(file_sunrise_swap_v1_route, 5);

/**
 * RouteResultParallel
 *
 * @generated from message sunrise.swap.v1.RouteResultParallel
 */
export type RouteResultParallel = Message<"sunrise.swap.v1.RouteResultParallel"> & {
  /**
   * @generated from field: repeated sunrise.swap.v1.RouteResult route_results = 1;
   */
  routeResults: RouteResult[];
};

/**
 * Describes the message sunrise.swap.v1.RouteResultParallel.
 * Use `create(RouteResultParallelSchema)` to create a new message.
 */
export const RouteResultParallelSchema: GenMessage<RouteResultParallel> = /*@__PURE__*/
  messageDesc(file_sunrise_swap_v1_route, 6);

/**
 * RouteResult
 *
 * @generated from message sunrise.swap.v1.RouteResult
 */
export type RouteResult = Message<"sunrise.swap.v1.RouteResult"> & {
  /**
   * @generated from field: cosmos.base.v1beta1.Coin token_in = 1;
   */
  tokenIn?: Coin;

  /**
   * @generated from field: cosmos.base.v1beta1.Coin token_out = 2;
   */
  tokenOut?: Coin;

  /**
   * strategy
   *
   * @generated from oneof sunrise.swap.v1.RouteResult.strategy
   */
  strategy: {
    /**
     * @generated from field: sunrise.swap.v1.RouteResultPool pool = 3;
     */
    value: RouteResultPool;
    case: "pool";
  } | {
    /**
     * @generated from field: sunrise.swap.v1.RouteResultSeries series = 4;
     */
    value: RouteResultSeries;
    case: "series";
  } | {
    /**
     * @generated from field: sunrise.swap.v1.RouteResultParallel parallel = 5;
     */
    value: RouteResultParallel;
    case: "parallel";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message sunrise.swap.v1.RouteResult.
 * Use `create(RouteResultSchema)` to create a new message.
 */
export const RouteResultSchema: GenMessage<RouteResult> = /*@__PURE__*/
  messageDesc(file_sunrise_swap_v1_route, 7);

