// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file cosmos/base/v1beta1/coin.proto (package cosmos.base.v1beta1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_gogoproto_gogo } from "../../../gogoproto/gogo_pb";
import { file_cosmos_proto_cosmos } from "../../../cosmos_proto/cosmos_pb";
import { file_amino_amino } from "../../../amino/amino_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file cosmos/base/v1beta1/coin.proto.
 */
export const file_cosmos_base_v1beta1_coin: GenFile = /*@__PURE__*/
  fileDesc("Ch5jb3Ntb3MvYmFzZS92MWJldGExL2NvaW4ucHJvdG8SE2Nvc21vcy5iYXNlLnYxYmV0YTEiXQoEQ29pbhINCgVkZW5vbRgBIAEoCRJACgZhbW91bnQYAiABKAlCMMjeHwDa3h8VY29zbW9zc2RrLmlvL21hdGguSW500rQtCmNvc21vcy5JbnSo57AqAToE6KAfASJhCgdEZWNDb2luEg0KBWRlbm9tGAEgASgJEkEKBmFtb3VudBgCIAEoCUIxyN4fANreHxtjb3Ntb3NzZGsuaW8vbWF0aC5MZWdhY3lEZWPStC0KY29zbW9zLkRlYzoE6KAfAUK+AQoXY29tLmNvc21vcy5iYXNlLnYxYmV0YTFCCUNvaW5Qcm90b1ABWiJnaXRodWIuY29tL2Nvc21vcy9jb3Ntb3Mtc2RrL3R5cGVzogIDQ0JYqgITQ29zbW9zLkJhc2UuVjFiZXRhMcoCE0Nvc21vc1xCYXNlXFYxYmV0YTHiAh9Db3Ntb3NcQmFzZVxWMWJldGExXEdQQk1ldGFkYXRh6gIVQ29zbW9zOjpCYXNlOjpWMWJldGEx2OEeAIDiHgBiBnByb3RvMw", [file_gogoproto_gogo, file_cosmos_proto_cosmos, file_amino_amino]);

/**
 * Coin defines a token with a denomination and an amount.
 *
 * NOTE: The amount field is an Int which implements the custom method
 * signatures required by gogoproto.
 *
 * @generated from message cosmos.base.v1beta1.Coin
 */
export type Coin = Message<"cosmos.base.v1beta1.Coin"> & {
  /**
   * @generated from field: string denom = 1;
   */
  denom: string;

  /**
   * @generated from field: string amount = 2;
   */
  amount: string;
};

/**
 * Describes the message cosmos.base.v1beta1.Coin.
 * Use `create(CoinSchema)` to create a new message.
 */
export const CoinSchema: GenMessage<Coin> = /*@__PURE__*/
  messageDesc(file_cosmos_base_v1beta1_coin, 0);

/**
 * DecCoin defines a token with a denomination and a decimal amount.
 *
 * NOTE: The amount field is an Dec which implements the custom method
 * signatures required by gogoproto.
 *
 * @generated from message cosmos.base.v1beta1.DecCoin
 */
export type DecCoin = Message<"cosmos.base.v1beta1.DecCoin"> & {
  /**
   * @generated from field: string denom = 1;
   */
  denom: string;

  /**
   * @generated from field: string amount = 2;
   */
  amount: string;
};

/**
 * Describes the message cosmos.base.v1beta1.DecCoin.
 * Use `create(DecCoinSchema)` to create a new message.
 */
export const DecCoinSchema: GenMessage<DecCoin> = /*@__PURE__*/
  messageDesc(file_cosmos_base_v1beta1_coin, 1);

