// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file sunrise/tokenconverter/v1/tx.proto (package sunrise.tokenconverter.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_cosmos_msg_v1_msg } from "../../../cosmos/msg/v1/msg_pb";
import { file_cosmos_proto_cosmos } from "../../../cosmos_proto/cosmos_pb";
import { file_gogoproto_gogo } from "../../../gogoproto/gogo_pb";
import type { Params } from "./params_pb";
import { file_sunrise_tokenconverter_v1_params } from "./params_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file sunrise/tokenconverter/v1/tx.proto.
 */
export const file_sunrise_tokenconverter_v1_tx: GenFile = /*@__PURE__*/
  fileDesc("CiJzdW5yaXNlL3Rva2VuY29udmVydGVyL3YxL3R4LnByb3RvEhlzdW5yaXNlLnRva2VuY29udmVydGVyLnYxIocBCg9Nc2dVcGRhdGVQYXJhbXMSKwoJYXV0aG9yaXR5GAEgASgJQhjStC0UY29zbW9zLkFkZHJlc3NTdHJpbmcSNwoGcGFyYW1zGAIgASgLMiEuc3VucmlzZS50b2tlbmNvbnZlcnRlci52MS5QYXJhbXNCBMjeHwA6DoLnsCoJYXV0aG9yaXR5IhkKF01zZ1VwZGF0ZVBhcmFtc1Jlc3BvbnNlIoABCgpNc2dDb252ZXJ0EigKBnNlbmRlchgBIAEoCUIY0rQtFGNvc21vcy5BZGRyZXNzU3RyaW5nEjsKBmFtb3VudBgCIAEoCUIryN4fANreHxVjb3Ntb3NzZGsuaW8vbWF0aC5JbnTStC0KY29zbW9zLkludDoLguewKgZzZW5kZXIiFAoSTXNnQ29udmVydFJlc3BvbnNlMt0BCgNNc2cSbgoMVXBkYXRlUGFyYW1zEiouc3VucmlzZS50b2tlbmNvbnZlcnRlci52MS5Nc2dVcGRhdGVQYXJhbXMaMi5zdW5yaXNlLnRva2VuY29udmVydGVyLnYxLk1zZ1VwZGF0ZVBhcmFtc1Jlc3BvbnNlEl8KB0NvbnZlcnQSJS5zdW5yaXNlLnRva2VuY29udmVydGVyLnYxLk1zZ0NvbnZlcnQaLS5zdW5yaXNlLnRva2VuY29udmVydGVyLnYxLk1zZ0NvbnZlcnRSZXNwb25zZRoFgOewKgFC5gEKHWNvbS5zdW5yaXNlLnRva2VuY29udmVydGVyLnYxQgdUeFByb3RvUAFaNmdpdGh1Yi5jb20vc3VucmlzZWxheWVyL3N1bnJpc2UveC90b2tlbmNvbnZlcnRlci90eXBlc6ICA1NUWKoCGVN1bnJpc2UuVG9rZW5jb252ZXJ0ZXIuVjHKAhlTdW5yaXNlXFRva2VuY29udmVydGVyXFYx4gIlU3VucmlzZVxUb2tlbmNvbnZlcnRlclxWMVxHUEJNZXRhZGF0YeoCG1N1bnJpc2U6OlRva2VuY29udmVydGVyOjpWMWIGcHJvdG8z", [file_cosmos_msg_v1_msg, file_cosmos_proto_cosmos, file_gogoproto_gogo, file_sunrise_tokenconverter_v1_params]);

/**
 * MsgUpdateParams is the Msg/UpdateParams request type.
 *
 * @generated from message sunrise.tokenconverter.v1.MsgUpdateParams
 */
export type MsgUpdateParams = Message<"sunrise.tokenconverter.v1.MsgUpdateParams"> & {
  /**
   * authority is the address that controls the module (defaults to x/gov unless overwritten).
   *
   * @generated from field: string authority = 1;
   */
  authority: string;

  /**
   * NOTE: All parameters must be supplied.
   *
   * @generated from field: sunrise.tokenconverter.v1.Params params = 2;
   */
  params?: Params;
};

/**
 * Describes the message sunrise.tokenconverter.v1.MsgUpdateParams.
 * Use `create(MsgUpdateParamsSchema)` to create a new message.
 */
export const MsgUpdateParamsSchema: GenMessage<MsgUpdateParams> = /*@__PURE__*/
  messageDesc(file_sunrise_tokenconverter_v1_tx, 0);

/**
 * MsgUpdateParamsResponse defines the response structure for executing a
 * MsgUpdateParams message.
 *
 * @generated from message sunrise.tokenconverter.v1.MsgUpdateParamsResponse
 */
export type MsgUpdateParamsResponse = Message<"sunrise.tokenconverter.v1.MsgUpdateParamsResponse"> & {
};

/**
 * Describes the message sunrise.tokenconverter.v1.MsgUpdateParamsResponse.
 * Use `create(MsgUpdateParamsResponseSchema)` to create a new message.
 */
export const MsgUpdateParamsResponseSchema: GenMessage<MsgUpdateParamsResponse> = /*@__PURE__*/
  messageDesc(file_sunrise_tokenconverter_v1_tx, 1);

/**
 * MsgConvert
 *
 * @generated from message sunrise.tokenconverter.v1.MsgConvert
 */
export type MsgConvert = Message<"sunrise.tokenconverter.v1.MsgConvert"> & {
  /**
   * @generated from field: string sender = 1;
   */
  sender: string;

  /**
   * Amount of bond denom
   *
   * @generated from field: string amount = 2;
   */
  amount: string;
};

/**
 * Describes the message sunrise.tokenconverter.v1.MsgConvert.
 * Use `create(MsgConvertSchema)` to create a new message.
 */
export const MsgConvertSchema: GenMessage<MsgConvert> = /*@__PURE__*/
  messageDesc(file_sunrise_tokenconverter_v1_tx, 2);

/**
 * MsgConvertResponse
 *
 * @generated from message sunrise.tokenconverter.v1.MsgConvertResponse
 */
export type MsgConvertResponse = Message<"sunrise.tokenconverter.v1.MsgConvertResponse"> & {
};

/**
 * Describes the message sunrise.tokenconverter.v1.MsgConvertResponse.
 * Use `create(MsgConvertResponseSchema)` to create a new message.
 */
export const MsgConvertResponseSchema: GenMessage<MsgConvertResponse> = /*@__PURE__*/
  messageDesc(file_sunrise_tokenconverter_v1_tx, 3);

/**
 * Msg defines the Msg service.
 *
 * @generated from service sunrise.tokenconverter.v1.Msg
 */
export const Msg: GenService<{
  /**
   * UpdateParams defines a (governance) operation for updating the module
   * parameters. The authority defaults to the x/gov module account.
   *
   * @generated from rpc sunrise.tokenconverter.v1.Msg.UpdateParams
   */
  updateParams: {
    methodKind: "unary";
    input: typeof MsgUpdateParamsSchema;
    output: typeof MsgUpdateParamsResponseSchema;
  },
  /**
   * Convert
   *
   * @generated from rpc sunrise.tokenconverter.v1.Msg.Convert
   */
  convert: {
    methodKind: "unary";
    input: typeof MsgConvertSchema;
    output: typeof MsgConvertResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_sunrise_tokenconverter_v1_tx, 0);

