// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file cosmos/mint/v1beta1/mint.proto (package cosmos.mint.v1beta1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_gogoproto_gogo } from "../../../gogoproto/gogo_pb";
import { file_cosmos_proto_cosmos } from "../../../cosmos_proto/cosmos_pb";
import { file_amino_amino } from "../../../amino/amino_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file cosmos/mint/v1beta1/mint.proto.
 */
export const file_cosmos_mint_v1beta1_mint: GenFile = /*@__PURE__*/
  fileDesc("Ch5jb3Ntb3MvbWludC92MWJldGExL21pbnQucHJvdG8SE2Nvc21vcy5taW50LnYxYmV0YTEiqgEKBk1pbnRlchJECglpbmZsYXRpb24YASABKAlCMcjeHwDa3h8bY29zbW9zc2RrLmlvL21hdGguTGVnYWN5RGVj0rQtCmNvc21vcy5EZWMSTAoRYW5udWFsX3Byb3Zpc2lvbnMYAiABKAlCMcjeHwDa3h8bY29zbW9zc2RrLmlvL21hdGguTGVnYWN5RGVj0rQtCmNvc21vcy5EZWMSDAoEZGF0YRgDIAEoDCLXAwoGUGFyYW1zEhIKCm1pbnRfZGVub20YASABKAkSVQoVaW5mbGF0aW9uX3JhdGVfY2hhbmdlGAIgASgJQjbI3h8A2t4fG2Nvc21vc3Nkay5pby9tYXRoLkxlZ2FjeURlY9K0LQpjb3Ntb3MuRGVjqOewKgESTQoNaW5mbGF0aW9uX21heBgDIAEoCUI2yN4fANreHxtjb3Ntb3NzZGsuaW8vbWF0aC5MZWdhY3lEZWPStC0KY29zbW9zLkRlY6jnsCoBEk0KDWluZmxhdGlvbl9taW4YBCABKAlCNsjeHwDa3h8bY29zbW9zc2RrLmlvL21hdGguTGVnYWN5RGVj0rQtCmNvc21vcy5EZWOo57AqARJLCgtnb2FsX2JvbmRlZBgFIAEoCUI2yN4fANreHxtjb3Ntb3NzZGsuaW8vbWF0aC5MZWdhY3lEZWPStC0KY29zbW9zLkRlY6jnsCoBEhcKD2Jsb2Nrc19wZXJfeWVhchgGIAEoBBI/CgptYXhfc3VwcGx5GAcgASgJQivI3h8A2t4fFWNvc21vc3Nkay5pby9tYXRoLkludNK0LQpjb3Ntb3MuSW50Oh2K57AqGGNvc21vcy1zZGsveC9taW50L1BhcmFtc0KtAQoXY29tLmNvc21vcy5taW50LnYxYmV0YTFCCU1pbnRQcm90b1ABWhljb3Ntb3NzZGsuaW8veC9taW50L3R5cGVzogIDQ01YqgITQ29zbW9zLk1pbnQuVjFiZXRhMcoCE0Nvc21vc1xNaW50XFYxYmV0YTHiAh9Db3Ntb3NcTWludFxWMWJldGExXEdQQk1ldGFkYXRh6gIVQ29zbW9zOjpNaW50OjpWMWJldGExYgZwcm90bzM", [file_gogoproto_gogo, file_cosmos_proto_cosmos, file_amino_amino]);

/**
 * Minter represents the minting state.
 *
 * @generated from message cosmos.mint.v1beta1.Minter
 */
export type Minter = Message<"cosmos.mint.v1beta1.Minter"> & {
  /**
   * current annual inflation rate
   *
   * @generated from field: string inflation = 1;
   */
  inflation: string;

  /**
   * current annual expected provisions
   *
   * @generated from field: string annual_provisions = 2;
   */
  annualProvisions: string;

  /**
   * data is any custom data that the user might want to put in the minter, to
   * be used in the minting process.
   *
   * @generated from field: bytes data = 3;
   */
  data: Uint8Array;
};

/**
 * Describes the message cosmos.mint.v1beta1.Minter.
 * Use `create(MinterSchema)` to create a new message.
 */
export const MinterSchema: GenMessage<Minter> = /*@__PURE__*/
  messageDesc(file_cosmos_mint_v1beta1_mint, 0);

/**
 * Params defines the parameters for the x/mint module.
 *
 * @generated from message cosmos.mint.v1beta1.Params
 */
export type Params = Message<"cosmos.mint.v1beta1.Params"> & {
  /**
   * type of coin to mint
   *
   * @generated from field: string mint_denom = 1;
   */
  mintDenom: string;

  /**
   * maximum annual change in inflation rate
   *
   * @generated from field: string inflation_rate_change = 2;
   */
  inflationRateChange: string;

  /**
   * maximum inflation rate
   *
   * @generated from field: string inflation_max = 3;
   */
  inflationMax: string;

  /**
   * minimum inflation rate
   *
   * @generated from field: string inflation_min = 4;
   */
  inflationMin: string;

  /**
   * goal of percent bonded atoms
   *
   * @generated from field: string goal_bonded = 5;
   */
  goalBonded: string;

  /**
   * expected blocks per year
   *
   * @generated from field: uint64 blocks_per_year = 6;
   */
  blocksPerYear: bigint;

  /**
   * maximum supply for the token
   *
   * @generated from field: string max_supply = 7;
   */
  maxSupply: string;
};

/**
 * Describes the message cosmos.mint.v1beta1.Params.
 * Use `create(ParamsSchema)` to create a new message.
 */
export const ParamsSchema: GenMessage<Params> = /*@__PURE__*/
  messageDesc(file_cosmos_mint_v1beta1_mint, 1);

