// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file sunrise/fee/v1/tx.proto (package sunrise.fee.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_cosmos_msg_v1_msg } from "../../../cosmos/msg/v1/msg_pb";
import { file_cosmos_proto_cosmos } from "../../../cosmos_proto/cosmos_pb";
import { file_gogoproto_gogo } from "../../../gogoproto/gogo_pb";
import type { Params } from "./params_pb";
import { file_sunrise_fee_v1_params } from "./params_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file sunrise/fee/v1/tx.proto.
 */
export const file_sunrise_fee_v1_tx: GenFile = /*@__PURE__*/
  fileDesc("ChdzdW5yaXNlL2ZlZS92MS90eC5wcm90bxIOc3VucmlzZS5mZWUudjEifAoPTXNnVXBkYXRlUGFyYW1zEisKCWF1dGhvcml0eRgBIAEoCUIY0rQtFGNvc21vcy5BZGRyZXNzU3RyaW5nEiwKBnBhcmFtcxgCIAEoCzIWLnN1bnJpc2UuZmVlLnYxLlBhcmFtc0IEyN4fADoOguewKglhdXRob3JpdHkiGQoXTXNnVXBkYXRlUGFyYW1zUmVzcG9uc2UyZgoDTXNnElgKDFVwZGF0ZVBhcmFtcxIfLnN1bnJpc2UuZmVlLnYxLk1zZ1VwZGF0ZVBhcmFtcxonLnN1bnJpc2UuZmVlLnYxLk1zZ1VwZGF0ZVBhcmFtc1Jlc3BvbnNlGgWA57AqAUKkAQoSY29tLnN1bnJpc2UuZmVlLnYxQgdUeFByb3RvUAFaK2dpdGh1Yi5jb20vc3VucmlzZWxheWVyL3N1bnJpc2UveC9mZWUvdHlwZXOiAgNTRliqAg5TdW5yaXNlLkZlZS5WMcoCDlN1bnJpc2VcRmVlXFYx4gIaU3VucmlzZVxGZWVcVjFcR1BCTWV0YWRhdGHqAhBTdW5yaXNlOjpGZWU6OlYxYgZwcm90bzM", [file_cosmos_msg_v1_msg, file_cosmos_proto_cosmos, file_gogoproto_gogo, file_sunrise_fee_v1_params]);

/**
 * MsgUpdateParams is the Msg/UpdateParams request type.
 *
 * @generated from message sunrise.fee.v1.MsgUpdateParams
 */
export type MsgUpdateParams = Message<"sunrise.fee.v1.MsgUpdateParams"> & {
  /**
   * authority is the address that controls the module (defaults to x/gov unless overwritten).
   *
   * @generated from field: string authority = 1;
   */
  authority: string;

  /**
   * params defines the module parameters to update.
   *
   * NOTE: All parameters must be supplied.
   *
   * @generated from field: sunrise.fee.v1.Params params = 2;
   */
  params?: Params;
};

/**
 * Describes the message sunrise.fee.v1.MsgUpdateParams.
 * Use `create(MsgUpdateParamsSchema)` to create a new message.
 */
export const MsgUpdateParamsSchema: GenMessage<MsgUpdateParams> = /*@__PURE__*/
  messageDesc(file_sunrise_fee_v1_tx, 0);

/**
 * MsgUpdateParamsResponse defines the response structure for executing a
 * MsgUpdateParams message.
 *
 * @generated from message sunrise.fee.v1.MsgUpdateParamsResponse
 */
export type MsgUpdateParamsResponse = Message<"sunrise.fee.v1.MsgUpdateParamsResponse"> & {
};

/**
 * Describes the message sunrise.fee.v1.MsgUpdateParamsResponse.
 * Use `create(MsgUpdateParamsResponseSchema)` to create a new message.
 */
export const MsgUpdateParamsResponseSchema: GenMessage<MsgUpdateParamsResponse> = /*@__PURE__*/
  messageDesc(file_sunrise_fee_v1_tx, 1);

/**
 * Msg defines the Msg service.
 *
 * @generated from service sunrise.fee.v1.Msg
 */
export const Msg: GenService<{
  /**
   * UpdateParams defines a (governance) operation for updating the module
   * parameters. The authority defaults to the x/gov module account.
   *
   * @generated from rpc sunrise.fee.v1.Msg.UpdateParams
   */
  updateParams: {
    methodKind: "unary";
    input: typeof MsgUpdateParamsSchema;
    output: typeof MsgUpdateParamsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_sunrise_fee_v1_tx, 0);

