// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file sunrise/selfdelegation/v1/query.proto (package sunrise.selfdelegation.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_gogoproto_gogo } from "../../../gogoproto/gogo_pb";
import { file_google_api_annotations } from "../../../google/api/annotations_pb";
import type { Params } from "./params_pb";
import { file_sunrise_selfdelegation_v1_params } from "./params_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file sunrise/selfdelegation/v1/query.proto.
 */
export const file_sunrise_selfdelegation_v1_query: GenFile = /*@__PURE__*/
  fileDesc("CiVzdW5yaXNlL3NlbGZkZWxlZ2F0aW9uL3YxL3F1ZXJ5LnByb3RvEhlzdW5yaXNlLnNlbGZkZWxlZ2F0aW9uLnYxIhQKElF1ZXJ5UGFyYW1zUmVxdWVzdCJOChNRdWVyeVBhcmFtc1Jlc3BvbnNlEjcKBnBhcmFtcxgBIAEoCzIhLnN1bnJpc2Uuc2VsZmRlbGVnYXRpb24udjEuUGFyYW1zQgTI3h8AIkYKLVF1ZXJ5U2VsZkRlbGVnYXRpb25Qcm94eUFjY291bnRCeU93bmVyUmVxdWVzdBIVCg1vd25lcl9hZGRyZXNzGAEgASgJIl8KLlF1ZXJ5U2VsZkRlbGVnYXRpb25Qcm94eUFjY291bnRCeU93bmVyUmVzcG9uc2USLQolc2VsZl9kZWxlZ2F0aW9uX3Byb3h5X2FjY291bnRfYWRkcmVzcxgBIAEoCSI6CiFRdWVyeUxvY2t1cEFjY291bnRzQnlPd25lclJlcXVlc3QSFQoNb3duZXJfYWRkcmVzcxgBIAEoCSJGCiJRdWVyeUxvY2t1cEFjY291bnRzQnlPd25lclJlc3BvbnNlEiAKGGxvY2t1cF9hY2NvdW50X2FkZHJlc3NlcxgBIAMoCTKWBQoFUXVlcnkSkgEKBlBhcmFtcxItLnN1bnJpc2Uuc2VsZmRlbGVnYXRpb24udjEuUXVlcnlQYXJhbXNSZXF1ZXN0Gi4uc3VucmlzZS5zZWxmZGVsZWdhdGlvbi52MS5RdWVyeVBhcmFtc1Jlc3BvbnNlIimC0+STAiMSIS9zdW5yaXNlL3NlbGZkZWxlZ2F0aW9uL3YxL3BhcmFtcxKTAgohU2VsZkRlbGVnYXRpb25Qcm94eUFjY291bnRCeU93bmVyEkguc3VucmlzZS5zZWxmZGVsZWdhdGlvbi52MS5RdWVyeVNlbGZEZWxlZ2F0aW9uUHJveHlBY2NvdW50QnlPd25lclJlcXVlc3QaSS5zdW5yaXNlLnNlbGZkZWxlZ2F0aW9uLnYxLlF1ZXJ5U2VsZkRlbGVnYXRpb25Qcm94eUFjY291bnRCeU93bmVyUmVzcG9uc2UiWYLT5JMCUxJRL3N1bnJpc2Uvc2VsZmRlbGVnYXRpb24vdjEvc2VsZl9kZWxlZ2F0aW9uX3Byb3h5X2FjY291bnRfYnlfb3duZXIve293bmVyX2FkZHJlc3N9EuEBChVMb2NrdXBBY2NvdW50c0J5T3duZXISPC5zdW5yaXNlLnNlbGZkZWxlZ2F0aW9uLnYxLlF1ZXJ5TG9ja3VwQWNjb3VudHNCeU93bmVyUmVxdWVzdBo9LnN1bnJpc2Uuc2VsZmRlbGVnYXRpb24udjEuUXVlcnlMb2NrdXBBY2NvdW50c0J5T3duZXJSZXNwb25zZSJLgtPkkwJFEkMvc3VucmlzZS9zZWxmZGVsZWdhdGlvbi92MS9sb2NrdXBfYWNjb3VudHNfYnlfb3duZXIve293bmVyX2FkZHJlc3N9QukBCh1jb20uc3VucmlzZS5zZWxmZGVsZWdhdGlvbi52MUIKUXVlcnlQcm90b1ABWjZnaXRodWIuY29tL3N1bnJpc2VsYXllci9zdW5yaXNlL3gvc2VsZmRlbGVnYXRpb24vdHlwZXOiAgNTU1iqAhlTdW5yaXNlLlNlbGZkZWxlZ2F0aW9uLlYxygIZU3VucmlzZVxTZWxmZGVsZWdhdGlvblxWMeICJVN1bnJpc2VcU2VsZmRlbGVnYXRpb25cVjFcR1BCTWV0YWRhdGHqAhtTdW5yaXNlOjpTZWxmZGVsZWdhdGlvbjo6VjFiBnByb3RvMw", [file_gogoproto_gogo, file_google_api_annotations, file_sunrise_selfdelegation_v1_params]);

/**
 * QueryParamsRequest is request type for the Query/Params RPC method.
 *
 * @generated from message sunrise.selfdelegation.v1.QueryParamsRequest
 */
export type QueryParamsRequest = Message<"sunrise.selfdelegation.v1.QueryParamsRequest"> & {
};

/**
 * Describes the message sunrise.selfdelegation.v1.QueryParamsRequest.
 * Use `create(QueryParamsRequestSchema)` to create a new message.
 */
export const QueryParamsRequestSchema: GenMessage<QueryParamsRequest> = /*@__PURE__*/
  messageDesc(file_sunrise_selfdelegation_v1_query, 0);

/**
 * QueryParamsResponse is response type for the Query/Params RPC method.
 *
 * @generated from message sunrise.selfdelegation.v1.QueryParamsResponse
 */
export type QueryParamsResponse = Message<"sunrise.selfdelegation.v1.QueryParamsResponse"> & {
  /**
   * params holds all the parameters of this module.
   *
   * @generated from field: sunrise.selfdelegation.v1.Params params = 1;
   */
  params?: Params;
};

/**
 * Describes the message sunrise.selfdelegation.v1.QueryParamsResponse.
 * Use `create(QueryParamsResponseSchema)` to create a new message.
 */
export const QueryParamsResponseSchema: GenMessage<QueryParamsResponse> = /*@__PURE__*/
  messageDesc(file_sunrise_selfdelegation_v1_query, 1);

/**
 * QuerySelfDelegationProxyAccountByOwnerRequest is request type for the Query/SelfDelegationProxyAccountByOwner RPC method.
 *
 * @generated from message sunrise.selfdelegation.v1.QuerySelfDelegationProxyAccountByOwnerRequest
 */
export type QuerySelfDelegationProxyAccountByOwnerRequest = Message<"sunrise.selfdelegation.v1.QuerySelfDelegationProxyAccountByOwnerRequest"> & {
  /**
   * @generated from field: string owner_address = 1;
   */
  ownerAddress: string;
};

/**
 * Describes the message sunrise.selfdelegation.v1.QuerySelfDelegationProxyAccountByOwnerRequest.
 * Use `create(QuerySelfDelegationProxyAccountByOwnerRequestSchema)` to create a new message.
 */
export const QuerySelfDelegationProxyAccountByOwnerRequestSchema: GenMessage<QuerySelfDelegationProxyAccountByOwnerRequest> = /*@__PURE__*/
  messageDesc(file_sunrise_selfdelegation_v1_query, 2);

/**
 * QuerySelfDelegationProxyAccountByOwnerResponse is response type for the Query/SelfDelegationProxyAccountByOwner RPC method.
 *
 * @generated from message sunrise.selfdelegation.v1.QuerySelfDelegationProxyAccountByOwnerResponse
 */
export type QuerySelfDelegationProxyAccountByOwnerResponse = Message<"sunrise.selfdelegation.v1.QuerySelfDelegationProxyAccountByOwnerResponse"> & {
  /**
   * @generated from field: string self_delegation_proxy_account_address = 1;
   */
  selfDelegationProxyAccountAddress: string;
};

/**
 * Describes the message sunrise.selfdelegation.v1.QuerySelfDelegationProxyAccountByOwnerResponse.
 * Use `create(QuerySelfDelegationProxyAccountByOwnerResponseSchema)` to create a new message.
 */
export const QuerySelfDelegationProxyAccountByOwnerResponseSchema: GenMessage<QuerySelfDelegationProxyAccountByOwnerResponse> = /*@__PURE__*/
  messageDesc(file_sunrise_selfdelegation_v1_query, 3);

/**
 * QueryLockupAccountsByOwnerRequest is request type for the Query/LockupAccountsByOwner RPC method.
 *
 * @generated from message sunrise.selfdelegation.v1.QueryLockupAccountsByOwnerRequest
 */
export type QueryLockupAccountsByOwnerRequest = Message<"sunrise.selfdelegation.v1.QueryLockupAccountsByOwnerRequest"> & {
  /**
   * @generated from field: string owner_address = 1;
   */
  ownerAddress: string;
};

/**
 * Describes the message sunrise.selfdelegation.v1.QueryLockupAccountsByOwnerRequest.
 * Use `create(QueryLockupAccountsByOwnerRequestSchema)` to create a new message.
 */
export const QueryLockupAccountsByOwnerRequestSchema: GenMessage<QueryLockupAccountsByOwnerRequest> = /*@__PURE__*/
  messageDesc(file_sunrise_selfdelegation_v1_query, 4);

/**
 * QueryLockupAccountsByOwnerResponse is response type for the Query/LockupAccountsByOwner RPC method.
 *
 * @generated from message sunrise.selfdelegation.v1.QueryLockupAccountsByOwnerResponse
 */
export type QueryLockupAccountsByOwnerResponse = Message<"sunrise.selfdelegation.v1.QueryLockupAccountsByOwnerResponse"> & {
  /**
   * @generated from field: repeated string lockup_account_addresses = 1;
   */
  lockupAccountAddresses: string[];
};

/**
 * Describes the message sunrise.selfdelegation.v1.QueryLockupAccountsByOwnerResponse.
 * Use `create(QueryLockupAccountsByOwnerResponseSchema)` to create a new message.
 */
export const QueryLockupAccountsByOwnerResponseSchema: GenMessage<QueryLockupAccountsByOwnerResponse> = /*@__PURE__*/
  messageDesc(file_sunrise_selfdelegation_v1_query, 5);

/**
 * Query defines the gRPC querier service.
 *
 * @generated from service sunrise.selfdelegation.v1.Query
 */
export const Query: GenService<{
  /**
   * Params queries the parameters of the module.
   *
   * @generated from rpc sunrise.selfdelegation.v1.Query.Params
   */
  params: {
    methodKind: "unary";
    input: typeof QueryParamsRequestSchema;
    output: typeof QueryParamsResponseSchema;
  },
  /**
   * SelfDelegationProxyAccountByOwner queries the SelfDelegationProxyAccount by owner address.
   *
   * @generated from rpc sunrise.selfdelegation.v1.Query.SelfDelegationProxyAccountByOwner
   */
  selfDelegationProxyAccountByOwner: {
    methodKind: "unary";
    input: typeof QuerySelfDelegationProxyAccountByOwnerRequestSchema;
    output: typeof QuerySelfDelegationProxyAccountByOwnerResponseSchema;
  },
  /**
   * LockupAccountsByOwner queries the LockupAccounts by owner address.
   *
   * @generated from rpc sunrise.selfdelegation.v1.Query.LockupAccountsByOwner
   */
  lockupAccountsByOwner: {
    methodKind: "unary";
    input: typeof QueryLockupAccountsByOwnerRequestSchema;
    output: typeof QueryLockupAccountsByOwnerResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_sunrise_selfdelegation_v1_query, 0);

