// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file sunrise/fee/query.proto (package sunrise.fee, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_amino_amino } from "../../amino/amino_pb";
import { file_gogoproto_gogo } from "../../gogoproto/gogo_pb";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import type { Params } from "./params_pb";
import { file_sunrise_fee_params } from "./params_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file sunrise/fee/query.proto.
 */
export const file_sunrise_fee_query: GenFile = /*@__PURE__*/
  fileDesc("ChdzdW5yaXNlL2ZlZS9xdWVyeS5wcm90bxILc3VucmlzZS5mZWUiFAoSUXVlcnlQYXJhbXNSZXF1ZXN0IkUKE1F1ZXJ5UGFyYW1zUmVzcG9uc2USLgoGcGFyYW1zGAEgASgLMhMuc3VucmlzZS5mZWUuUGFyYW1zQgnI3h8AqOewKgEycQoFUXVlcnkSaAoGUGFyYW1zEh8uc3VucmlzZS5mZWUuUXVlcnlQYXJhbXNSZXF1ZXN0GiAuc3VucmlzZS5mZWUuUXVlcnlQYXJhbXNSZXNwb25zZSIbgtPkkwIVEhMvc3VucmlzZS9mZWUvcGFyYW1zQpcBCg9jb20uc3VucmlzZS5mZWVCClF1ZXJ5UHJvdG9QAVorZ2l0aHViLmNvbS9zdW5yaXNlbGF5ZXIvc3VucmlzZS94L2ZlZS90eXBlc6ICA1NGWKoCC1N1bnJpc2UuRmVlygILU3VucmlzZVxGZWXiAhdTdW5yaXNlXEZlZVxHUEJNZXRhZGF0YeoCDFN1bnJpc2U6OkZlZWIGcHJvdG8z", [file_amino_amino, file_gogoproto_gogo, file_google_api_annotations, file_sunrise_fee_params]);

/**
 * QueryParamsRequest is request type for the Query/Params RPC method.
 *
 * @generated from message sunrise.fee.QueryParamsRequest
 */
export type QueryParamsRequest = Message<"sunrise.fee.QueryParamsRequest"> & {
};

/**
 * Describes the message sunrise.fee.QueryParamsRequest.
 * Use `create(QueryParamsRequestSchema)` to create a new message.
 */
export const QueryParamsRequestSchema: GenMessage<QueryParamsRequest> = /*@__PURE__*/
  messageDesc(file_sunrise_fee_query, 0);

/**
 * QueryParamsResponse is response type for the Query/Params RPC method.
 *
 * @generated from message sunrise.fee.QueryParamsResponse
 */
export type QueryParamsResponse = Message<"sunrise.fee.QueryParamsResponse"> & {
  /**
   * params holds all the parameters of this module.
   *
   * @generated from field: sunrise.fee.Params params = 1;
   */
  params?: Params;
};

/**
 * Describes the message sunrise.fee.QueryParamsResponse.
 * Use `create(QueryParamsResponseSchema)` to create a new message.
 */
export const QueryParamsResponseSchema: GenMessage<QueryParamsResponse> = /*@__PURE__*/
  messageDesc(file_sunrise_fee_query, 1);

/**
 * Query defines the gRPC querier service.
 *
 * @generated from service sunrise.fee.Query
 */
export const Query: GenService<{
  /**
   * Parameters queries the parameters of the module.
   *
   * @generated from rpc sunrise.fee.Query.Params
   */
  params: {
    methodKind: "unary";
    input: typeof QueryParamsRequestSchema;
    output: typeof QueryParamsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_sunrise_fee_query, 0);

