// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file sunrise/liquidityincentive/v1/gauge.proto (package sunrise.liquidityincentive.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_amino_amino } from "../../../amino/amino_pb";
import { file_cosmos_proto_cosmos } from "../../../cosmos_proto/cosmos_pb";
import { file_gogoproto_gogo } from "../../../gogoproto/gogo_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file sunrise/liquidityincentive/v1/gauge.proto.
 */
export const file_sunrise_liquidityincentive_v1_gauge: GenFile = /*@__PURE__*/
  fileDesc("CilzdW5yaXNlL2xpcXVpZGl0eWluY2VudGl2ZS92MS9nYXVnZS5wcm90bxIdc3VucmlzZS5saXF1aWRpdHlpbmNlbnRpdmUudjEidAoFR2F1Z2USGQoRcHJldmlvdXNfZXBvY2hfaWQYASABKAQSDwoHcG9vbF9pZBgCIAEoBBI/CgVjb3VudBgDIAEoCUIwyN4fANreHxVjb3Ntb3NzZGsuaW8vbWF0aC5JbnTStC0KY29zbW9zLkludKjnsCoBIl8KC1RhbGx5UmVzdWx0Eg8KB3Bvb2xfaWQYASABKAQSPwoFY291bnQYAiABKAlCMMjeHwDa3h8VY29zbW9zc2RrLmlvL21hdGguSW500rQtCmNvc21vcy5JbnSo57AqASI9CgpQb29sV2VpZ2h0Eg8KB3Bvb2xfaWQYASABKAQSHgoGd2VpZ2h0GAIgASgJQg7StC0KY29zbW9zLkRlYyJdCgRWb3RlEg4KBnNlbmRlchgBIAEoCRJFCgxwb29sX3dlaWdodHMYAiADKAsyKS5zdW5yaXNlLmxpcXVpZGl0eWluY2VudGl2ZS52MS5Qb29sV2VpZ2h0QgTI3h8AQoECCiFjb20uc3VucmlzZS5saXF1aWRpdHlpbmNlbnRpdmUudjFCCkdhdWdlUHJvdG9QAVo6Z2l0aHViLmNvbS9zdW5yaXNlbGF5ZXIvc3VucmlzZS94L2xpcXVpZGl0eWluY2VudGl2ZS90eXBlc6ICA1NMWKoCHVN1bnJpc2UuTGlxdWlkaXR5aW5jZW50aXZlLlYxygIdU3VucmlzZVxMaXF1aWRpdHlpbmNlbnRpdmVcVjHiAilTdW5yaXNlXExpcXVpZGl0eWluY2VudGl2ZVxWMVxHUEJNZXRhZGF0YeoCH1N1bnJpc2U6OkxpcXVpZGl0eWluY2VudGl2ZTo6VjFiBnByb3RvMw", [file_amino_amino, file_cosmos_proto_cosmos, file_gogoproto_gogo]);

/**
 * Gauge
 *
 * @generated from message sunrise.liquidityincentive.v1.Gauge
 */
export type Gauge = Message<"sunrise.liquidityincentive.v1.Gauge"> & {
  /**
   * @generated from field: uint64 previous_epoch_id = 1;
   */
  previousEpochId: bigint;

  /**
   * @generated from field: uint64 pool_id = 2;
   */
  poolId: bigint;

  /**
   * @generated from field: string count = 3;
   */
  count: string;
};

/**
 * Describes the message sunrise.liquidityincentive.v1.Gauge.
 * Use `create(GaugeSchema)` to create a new message.
 */
export const GaugeSchema: GenMessage<Gauge> = /*@__PURE__*/
  messageDesc(file_sunrise_liquidityincentive_v1_gauge, 0);

/**
 * TallyResult
 *
 * @generated from message sunrise.liquidityincentive.v1.TallyResult
 */
export type TallyResult = Message<"sunrise.liquidityincentive.v1.TallyResult"> & {
  /**
   * @generated from field: uint64 pool_id = 1;
   */
  poolId: bigint;

  /**
   * @generated from field: string count = 2;
   */
  count: string;
};

/**
 * Describes the message sunrise.liquidityincentive.v1.TallyResult.
 * Use `create(TallyResultSchema)` to create a new message.
 */
export const TallyResultSchema: GenMessage<TallyResult> = /*@__PURE__*/
  messageDesc(file_sunrise_liquidityincentive_v1_gauge, 1);

/**
 * PoolWeight
 *
 * @generated from message sunrise.liquidityincentive.v1.PoolWeight
 */
export type PoolWeight = Message<"sunrise.liquidityincentive.v1.PoolWeight"> & {
  /**
   * @generated from field: uint64 pool_id = 1;
   */
  poolId: bigint;

  /**
   * @generated from field: string weight = 2;
   */
  weight: string;
};

/**
 * Describes the message sunrise.liquidityincentive.v1.PoolWeight.
 * Use `create(PoolWeightSchema)` to create a new message.
 */
export const PoolWeightSchema: GenMessage<PoolWeight> = /*@__PURE__*/
  messageDesc(file_sunrise_liquidityincentive_v1_gauge, 2);

/**
 * Vote
 *
 * @generated from message sunrise.liquidityincentive.v1.Vote
 */
export type Vote = Message<"sunrise.liquidityincentive.v1.Vote"> & {
  /**
   * @generated from field: string sender = 1;
   */
  sender: string;

  /**
   * @generated from field: repeated sunrise.liquidityincentive.v1.PoolWeight pool_weights = 2;
   */
  poolWeights: PoolWeight[];
};

/**
 * Describes the message sunrise.liquidityincentive.v1.Vote.
 * Use `create(VoteSchema)` to create a new message.
 */
export const VoteSchema: GenMessage<Vote> = /*@__PURE__*/
  messageDesc(file_sunrise_liquidityincentive_v1_gauge, 3);

