// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file sunrise/liquidityincentive/v1/tx.proto (package sunrise.liquidityincentive.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_cosmos_msg_v1_msg } from "../../../cosmos/msg/v1/msg_pb";
import { file_cosmos_proto_cosmos } from "../../../cosmos_proto/cosmos_pb";
import { file_gogoproto_gogo } from "../../../gogoproto/gogo_pb";
import type { PoolWeight } from "./gauge_pb";
import { file_sunrise_liquidityincentive_v1_gauge } from "./gauge_pb";
import type { Params } from "./params_pb";
import { file_sunrise_liquidityincentive_v1_params } from "./params_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file sunrise/liquidityincentive/v1/tx.proto.
 */
export const file_sunrise_liquidityincentive_v1_tx: GenFile = /*@__PURE__*/
  fileDesc("CiZzdW5yaXNlL2xpcXVpZGl0eWluY2VudGl2ZS92MS90eC5wcm90bxIdc3VucmlzZS5saXF1aWRpdHlpbmNlbnRpdmUudjEiiwEKD01zZ1VwZGF0ZVBhcmFtcxIrCglhdXRob3JpdHkYASABKAlCGNK0LRRjb3Ntb3MuQWRkcmVzc1N0cmluZxI7CgZwYXJhbXMYAiABKAsyJS5zdW5yaXNlLmxpcXVpZGl0eWluY2VudGl2ZS52MS5QYXJhbXNCBMjeHwA6DoLnsCoJYXV0aG9yaXR5IhkKF01zZ1VwZGF0ZVBhcmFtc1Jlc3BvbnNlIowBCgxNc2dWb3RlR2F1Z2USKAoGc2VuZGVyGAEgASgJQhjStC0UY29zbW9zLkFkZHJlc3NTdHJpbmcSRQoMcG9vbF93ZWlnaHRzGAIgAygLMikuc3VucmlzZS5saXF1aWRpdHlpbmNlbnRpdmUudjEuUG9vbFdlaWdodEIEyN4fADoLguewKgZzZW5kZXIiFgoUTXNnVm90ZUdhdWdlUmVzcG9uc2UiTgoVTXNnQ29sbGVjdFZvdGVSZXdhcmRzEigKBnNlbmRlchgBIAEoCUIY0rQtFGNvc21vcy5BZGRyZXNzU3RyaW5nOguC57AqBnNlbmRlciIfCh1Nc2dDb2xsZWN0Vm90ZVJld2FyZHNSZXNwb25zZTL+AgoDTXNnEnYKDFVwZGF0ZVBhcmFtcxIuLnN1bnJpc2UubGlxdWlkaXR5aW5jZW50aXZlLnYxLk1zZ1VwZGF0ZVBhcmFtcxo2LnN1bnJpc2UubGlxdWlkaXR5aW5jZW50aXZlLnYxLk1zZ1VwZGF0ZVBhcmFtc1Jlc3BvbnNlEm0KCVZvdGVHYXVnZRIrLnN1bnJpc2UubGlxdWlkaXR5aW5jZW50aXZlLnYxLk1zZ1ZvdGVHYXVnZRozLnN1bnJpc2UubGlxdWlkaXR5aW5jZW50aXZlLnYxLk1zZ1ZvdGVHYXVnZVJlc3BvbnNlEogBChJDb2xsZWN0Vm90ZVJld2FyZHMSNC5zdW5yaXNlLmxpcXVpZGl0eWluY2VudGl2ZS52MS5Nc2dDb2xsZWN0Vm90ZVJld2FyZHMaPC5zdW5yaXNlLmxpcXVpZGl0eWluY2VudGl2ZS52MS5Nc2dDb2xsZWN0Vm90ZVJld2FyZHNSZXNwb25zZRoFgOewKgFC/gEKIWNvbS5zdW5yaXNlLmxpcXVpZGl0eWluY2VudGl2ZS52MUIHVHhQcm90b1ABWjpnaXRodWIuY29tL3N1bnJpc2VsYXllci9zdW5yaXNlL3gvbGlxdWlkaXR5aW5jZW50aXZlL3R5cGVzogIDU0xYqgIdU3VucmlzZS5MaXF1aWRpdHlpbmNlbnRpdmUuVjHKAh1TdW5yaXNlXExpcXVpZGl0eWluY2VudGl2ZVxWMeICKVN1bnJpc2VcTGlxdWlkaXR5aW5jZW50aXZlXFYxXEdQQk1ldGFkYXRh6gIfU3VucmlzZTo6TGlxdWlkaXR5aW5jZW50aXZlOjpWMWIGcHJvdG8z", [file_cosmos_msg_v1_msg, file_cosmos_proto_cosmos, file_gogoproto_gogo, file_sunrise_liquidityincentive_v1_gauge, file_sunrise_liquidityincentive_v1_params]);

/**
 * MsgUpdateParams is the Msg/UpdateParams request type.
 *
 * @generated from message sunrise.liquidityincentive.v1.MsgUpdateParams
 */
export type MsgUpdateParams = Message<"sunrise.liquidityincentive.v1.MsgUpdateParams"> & {
  /**
   * authority is the address that controls the module (defaults to x/gov unless
   * overwritten).
   *
   * @generated from field: string authority = 1;
   */
  authority: string;

  /**
   * NOTE: All parameters must be supplied.
   *
   * @generated from field: sunrise.liquidityincentive.v1.Params params = 2;
   */
  params?: Params;
};

/**
 * Describes the message sunrise.liquidityincentive.v1.MsgUpdateParams.
 * Use `create(MsgUpdateParamsSchema)` to create a new message.
 */
export const MsgUpdateParamsSchema: GenMessage<MsgUpdateParams> = /*@__PURE__*/
  messageDesc(file_sunrise_liquidityincentive_v1_tx, 0);

/**
 * MsgUpdateParamsResponse defines the response structure for executing a
 * MsgUpdateParams message.
 *
 * @generated from message sunrise.liquidityincentive.v1.MsgUpdateParamsResponse
 */
export type MsgUpdateParamsResponse = Message<"sunrise.liquidityincentive.v1.MsgUpdateParamsResponse"> & {
};

/**
 * Describes the message sunrise.liquidityincentive.v1.MsgUpdateParamsResponse.
 * Use `create(MsgUpdateParamsResponseSchema)` to create a new message.
 */
export const MsgUpdateParamsResponseSchema: GenMessage<MsgUpdateParamsResponse> = /*@__PURE__*/
  messageDesc(file_sunrise_liquidityincentive_v1_tx, 1);

/**
 * MsgVoteGauge
 *
 * @generated from message sunrise.liquidityincentive.v1.MsgVoteGauge
 */
export type MsgVoteGauge = Message<"sunrise.liquidityincentive.v1.MsgVoteGauge"> & {
  /**
   * @generated from field: string sender = 1;
   */
  sender: string;

  /**
   * @generated from field: repeated sunrise.liquidityincentive.v1.PoolWeight pool_weights = 2;
   */
  poolWeights: PoolWeight[];
};

/**
 * Describes the message sunrise.liquidityincentive.v1.MsgVoteGauge.
 * Use `create(MsgVoteGaugeSchema)` to create a new message.
 */
export const MsgVoteGaugeSchema: GenMessage<MsgVoteGauge> = /*@__PURE__*/
  messageDesc(file_sunrise_liquidityincentive_v1_tx, 2);

/**
 * MsgVoteGaugeResponse
 *
 * @generated from message sunrise.liquidityincentive.v1.MsgVoteGaugeResponse
 */
export type MsgVoteGaugeResponse = Message<"sunrise.liquidityincentive.v1.MsgVoteGaugeResponse"> & {
};

/**
 * Describes the message sunrise.liquidityincentive.v1.MsgVoteGaugeResponse.
 * Use `create(MsgVoteGaugeResponseSchema)` to create a new message.
 */
export const MsgVoteGaugeResponseSchema: GenMessage<MsgVoteGaugeResponse> = /*@__PURE__*/
  messageDesc(file_sunrise_liquidityincentive_v1_tx, 3);

/**
 * MsgCollectVoteRewards
 *
 * @generated from message sunrise.liquidityincentive.v1.MsgCollectVoteRewards
 */
export type MsgCollectVoteRewards = Message<"sunrise.liquidityincentive.v1.MsgCollectVoteRewards"> & {
  /**
   * @generated from field: string sender = 1;
   */
  sender: string;
};

/**
 * Describes the message sunrise.liquidityincentive.v1.MsgCollectVoteRewards.
 * Use `create(MsgCollectVoteRewardsSchema)` to create a new message.
 */
export const MsgCollectVoteRewardsSchema: GenMessage<MsgCollectVoteRewards> = /*@__PURE__*/
  messageDesc(file_sunrise_liquidityincentive_v1_tx, 4);

/**
 * MsgCollectVoteRewardsResponse
 *
 * @generated from message sunrise.liquidityincentive.v1.MsgCollectVoteRewardsResponse
 */
export type MsgCollectVoteRewardsResponse = Message<"sunrise.liquidityincentive.v1.MsgCollectVoteRewardsResponse"> & {
};

/**
 * Describes the message sunrise.liquidityincentive.v1.MsgCollectVoteRewardsResponse.
 * Use `create(MsgCollectVoteRewardsResponseSchema)` to create a new message.
 */
export const MsgCollectVoteRewardsResponseSchema: GenMessage<MsgCollectVoteRewardsResponse> = /*@__PURE__*/
  messageDesc(file_sunrise_liquidityincentive_v1_tx, 5);

/**
 * Msg defines the Msg service.
 *
 * @generated from service sunrise.liquidityincentive.v1.Msg
 */
export const Msg: GenService<{
  /**
   * UpdateParams defines a (governance) operation for updating the module
   * parameters. The authority defaults to the x/gov module account.
   *
   * @generated from rpc sunrise.liquidityincentive.v1.Msg.UpdateParams
   */
  updateParams: {
    methodKind: "unary";
    input: typeof MsgUpdateParamsSchema;
    output: typeof MsgUpdateParamsResponseSchema;
  },
  /**
   * VoteGauge
   *
   * @generated from rpc sunrise.liquidityincentive.v1.Msg.VoteGauge
   */
  voteGauge: {
    methodKind: "unary";
    input: typeof MsgVoteGaugeSchema;
    output: typeof MsgVoteGaugeResponseSchema;
  },
  /**
   * CollectVoteRewards
   *
   * @generated from rpc sunrise.liquidityincentive.v1.Msg.CollectVoteRewards
   */
  collectVoteRewards: {
    methodKind: "unary";
    input: typeof MsgCollectVoteRewardsSchema;
    output: typeof MsgCollectVoteRewardsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_sunrise_liquidityincentive_v1_tx, 0);

