// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file sunrise/da/tx.proto (package sunrise.da, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_amino_amino } from "../../amino/amino_pb";
import { file_cosmos_msg_v1_msg } from "../../cosmos/msg/v1/msg_pb";
import { file_cosmos_proto_cosmos } from "../../cosmos_proto/cosmos_pb";
import { file_gogoproto_gogo } from "../../gogoproto/gogo_pb";
import type { Params } from "./params_pb";
import { file_sunrise_da_params } from "./params_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file sunrise/da/tx.proto.
 */
export const file_sunrise_da_tx: GenFile = /*@__PURE__*/
  fileDesc("ChNzdW5yaXNlL2RhL3R4LnByb3RvEgpzdW5yaXNlLmRhIp4BCg9Nc2dVcGRhdGVQYXJhbXMSKwoJYXV0aG9yaXR5GAEgASgJQhjStC0UY29zbW9zLkFkZHJlc3NTdHJpbmcSLQoGcGFyYW1zGAIgASgLMhIuc3VucmlzZS5kYS5QYXJhbXNCCcjeHwCo57AqATovguewKglhdXRob3JpdHmK57AqHHN1bnJpc2UveC9kYS9Nc2dVcGRhdGVQYXJhbXMiGQoXTXNnVXBkYXRlUGFyYW1zUmVzcG9uc2UisAEKDk1zZ1B1Ymxpc2hEYXRhEigKBnNlbmRlchgBIAEoCUIY0rQtFGNvc21vcy5BZGRyZXNzU3RyaW5nEhQKDG1ldGFkYXRhX3VyaRgCIAEoCRIaChJwYXJpdHlfc2hhcmRfY291bnQYAyABKAQSGwoTc2hhcmRfZG91YmxlX2hhc2hlcxgEIAMoDBIYChBkYXRhX3NvdXJjZV9pbmZvGAUgASgJOguC57AqBnNlbmRlciIYChZNc2dQdWJsaXNoRGF0YVJlc3BvbnNlImMKFE1zZ0NoYWxsZW5nZUZvckZyYXVkEigKBnNlbmRlchgBIAEoCUIY0rQtFGNvc21vcy5BZGRyZXNzU3RyaW5nEhQKDG1ldGFkYXRhX3VyaRgCIAEoCToLguewKgZzZW5kZXIiHgocTXNnQ2hhbGxlbmdlRm9yRnJhdWRSZXNwb25zZSKVAQoOTXNnU3VibWl0UHJvb2YSKAoGc2VuZGVyGAEgASgJQhjStC0UY29zbW9zLkFkZHJlc3NTdHJpbmcSFAoMbWV0YWRhdGFfdXJpGAIgASgJEg8KB2luZGljZXMYAyADKAMSDgoGcHJvb2ZzGAQgAygMEhUKDWlzX3ZhbGlkX2RhdGEYBSABKAg6C4LnsCoGc2VuZGVyIhgKFk1zZ1N1Ym1pdFByb29mUmVzcG9uc2Uy3QIKA01zZxJQCgxVcGRhdGVQYXJhbXMSGy5zdW5yaXNlLmRhLk1zZ1VwZGF0ZVBhcmFtcxojLnN1bnJpc2UuZGEuTXNnVXBkYXRlUGFyYW1zUmVzcG9uc2USTQoLUHVibGlzaERhdGESGi5zdW5yaXNlLmRhLk1zZ1B1Ymxpc2hEYXRhGiIuc3VucmlzZS5kYS5Nc2dQdWJsaXNoRGF0YVJlc3BvbnNlEl8KEUNoYWxsZW5nZUZvckZyYXVkEiAuc3VucmlzZS5kYS5Nc2dDaGFsbGVuZ2VGb3JGcmF1ZBooLnN1bnJpc2UuZGEuTXNnQ2hhbGxlbmdlRm9yRnJhdWRSZXNwb25zZRJNCgtTdWJtaXRQcm9vZhIaLnN1bnJpc2UuZGEuTXNnU3VibWl0UHJvb2YaIi5zdW5yaXNlLmRhLk1zZ1N1Ym1pdFByb29mUmVzcG9uc2UaBYDnsCoBQo4BCg5jb20uc3VucmlzZS5kYUIHVHhQcm90b1ABWipnaXRodWIuY29tL3N1bnJpc2VsYXllci9zdW5yaXNlL3gvZGEvdHlwZXOiAgNTRFiqAgpTdW5yaXNlLkRhygIKU3VucmlzZVxEYeICFlN1bnJpc2VcRGFcR1BCTWV0YWRhdGHqAgtTdW5yaXNlOjpEYWIGcHJvdG8z", [file_amino_amino, file_cosmos_msg_v1_msg, file_cosmos_proto_cosmos, file_gogoproto_gogo, file_sunrise_da_params]);

/**
 * MsgUpdateParams is the Msg/UpdateParams request type.
 *
 * @generated from message sunrise.da.MsgUpdateParams
 */
export type MsgUpdateParams = Message<"sunrise.da.MsgUpdateParams"> & {
  /**
   * authority is the address that controls the module (defaults to x/gov unless
   * overwritten).
   *
   * @generated from field: string authority = 1;
   */
  authority: string;

  /**
   * NOTE: All parameters must be supplied.
   *
   * @generated from field: sunrise.da.Params params = 2;
   */
  params?: Params;
};

/**
 * Describes the message sunrise.da.MsgUpdateParams.
 * Use `create(MsgUpdateParamsSchema)` to create a new message.
 */
export const MsgUpdateParamsSchema: GenMessage<MsgUpdateParams> = /*@__PURE__*/
  messageDesc(file_sunrise_da_tx, 0);

/**
 * MsgUpdateParamsResponse defines the response structure for executing a
 * MsgUpdateParams message.
 *
 * @generated from message sunrise.da.MsgUpdateParamsResponse
 */
export type MsgUpdateParamsResponse = Message<"sunrise.da.MsgUpdateParamsResponse"> & {
};

/**
 * Describes the message sunrise.da.MsgUpdateParamsResponse.
 * Use `create(MsgUpdateParamsResponseSchema)` to create a new message.
 */
export const MsgUpdateParamsResponseSchema: GenMessage<MsgUpdateParamsResponse> = /*@__PURE__*/
  messageDesc(file_sunrise_da_tx, 1);

/**
 * MsgPublishData
 *
 * @generated from message sunrise.da.MsgPublishData
 */
export type MsgPublishData = Message<"sunrise.da.MsgPublishData"> & {
  /**
   * @generated from field: string sender = 1;
   */
  sender: string;

  /**
   * @generated from field: string metadata_uri = 2;
   */
  metadataUri: string;

  /**
   * @generated from field: uint64 parity_shard_count = 3;
   */
  parityShardCount: bigint;

  /**
   * @generated from field: repeated bytes shard_double_hashes = 4;
   */
  shardDoubleHashes: Uint8Array[];

  /**
   * @generated from field: string data_source_info = 5;
   */
  dataSourceInfo: string;
};

/**
 * Describes the message sunrise.da.MsgPublishData.
 * Use `create(MsgPublishDataSchema)` to create a new message.
 */
export const MsgPublishDataSchema: GenMessage<MsgPublishData> = /*@__PURE__*/
  messageDesc(file_sunrise_da_tx, 2);

/**
 * MsgPublishDataResponse
 *
 * @generated from message sunrise.da.MsgPublishDataResponse
 */
export type MsgPublishDataResponse = Message<"sunrise.da.MsgPublishDataResponse"> & {
};

/**
 * Describes the message sunrise.da.MsgPublishDataResponse.
 * Use `create(MsgPublishDataResponseSchema)` to create a new message.
 */
export const MsgPublishDataResponseSchema: GenMessage<MsgPublishDataResponse> = /*@__PURE__*/
  messageDesc(file_sunrise_da_tx, 3);

/**
 * MsgChallengeForFraud
 *
 * @generated from message sunrise.da.MsgChallengeForFraud
 */
export type MsgChallengeForFraud = Message<"sunrise.da.MsgChallengeForFraud"> & {
  /**
   * @generated from field: string sender = 1;
   */
  sender: string;

  /**
   * @generated from field: string metadata_uri = 2;
   */
  metadataUri: string;
};

/**
 * Describes the message sunrise.da.MsgChallengeForFraud.
 * Use `create(MsgChallengeForFraudSchema)` to create a new message.
 */
export const MsgChallengeForFraudSchema: GenMessage<MsgChallengeForFraud> = /*@__PURE__*/
  messageDesc(file_sunrise_da_tx, 4);

/**
 * MsgChallengeForFraudResponse
 *
 * @generated from message sunrise.da.MsgChallengeForFraudResponse
 */
export type MsgChallengeForFraudResponse = Message<"sunrise.da.MsgChallengeForFraudResponse"> & {
};

/**
 * Describes the message sunrise.da.MsgChallengeForFraudResponse.
 * Use `create(MsgChallengeForFraudResponseSchema)` to create a new message.
 */
export const MsgChallengeForFraudResponseSchema: GenMessage<MsgChallengeForFraudResponse> = /*@__PURE__*/
  messageDesc(file_sunrise_da_tx, 5);

/**
 * MsgSubmitProof
 *
 * @generated from message sunrise.da.MsgSubmitProof
 */
export type MsgSubmitProof = Message<"sunrise.da.MsgSubmitProof"> & {
  /**
   * @generated from field: string sender = 1;
   */
  sender: string;

  /**
   * @generated from field: string metadata_uri = 2;
   */
  metadataUri: string;

  /**
   * @generated from field: repeated int64 indices = 3;
   */
  indices: bigint[];

  /**
   * @generated from field: repeated bytes proofs = 4;
   */
  proofs: Uint8Array[];

  /**
   * @generated from field: bool is_valid_data = 5;
   */
  isValidData: boolean;
};

/**
 * Describes the message sunrise.da.MsgSubmitProof.
 * Use `create(MsgSubmitProofSchema)` to create a new message.
 */
export const MsgSubmitProofSchema: GenMessage<MsgSubmitProof> = /*@__PURE__*/
  messageDesc(file_sunrise_da_tx, 6);

/**
 * MsgSubmitProofResponse
 *
 * @generated from message sunrise.da.MsgSubmitProofResponse
 */
export type MsgSubmitProofResponse = Message<"sunrise.da.MsgSubmitProofResponse"> & {
};

/**
 * Describes the message sunrise.da.MsgSubmitProofResponse.
 * Use `create(MsgSubmitProofResponseSchema)` to create a new message.
 */
export const MsgSubmitProofResponseSchema: GenMessage<MsgSubmitProofResponse> = /*@__PURE__*/
  messageDesc(file_sunrise_da_tx, 7);

/**
 * Msg defines the Msg service.
 *
 * @generated from service sunrise.da.Msg
 */
export const Msg: GenService<{
  /**
   * UpdateParams defines a (governance) operation for updating the module
   * parameters. The authority defaults to the x/gov module account.
   *
   * @generated from rpc sunrise.da.Msg.UpdateParams
   */
  updateParams: {
    methodKind: "unary";
    input: typeof MsgUpdateParamsSchema;
    output: typeof MsgUpdateParamsResponseSchema;
  },
  /**
   * PublishData
   *
   * @generated from rpc sunrise.da.Msg.PublishData
   */
  publishData: {
    methodKind: "unary";
    input: typeof MsgPublishDataSchema;
    output: typeof MsgPublishDataResponseSchema;
  },
  /**
   * ChallengeForFraud
   *
   * @generated from rpc sunrise.da.Msg.ChallengeForFraud
   */
  challengeForFraud: {
    methodKind: "unary";
    input: typeof MsgChallengeForFraudSchema;
    output: typeof MsgChallengeForFraudResponseSchema;
  },
  /**
   * SubmitProof
   *
   * @generated from rpc sunrise.da.Msg.SubmitProof
   */
  submitProof: {
    methodKind: "unary";
    input: typeof MsgSubmitProofSchema;
    output: typeof MsgSubmitProofResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_sunrise_da_tx, 0);

