// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file sunrise/accounts/self_delegatable_lockup/v1/lockup.proto (package sunrise.accounts.self_delegatable_lockup.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_amino_amino } from "../../../../amino/amino_pb";
import type { Coin } from "../../../../cosmos/base/v1beta1/coin_pb";
import { file_cosmos_base_v1beta1_coin } from "../../../../cosmos/base/v1beta1/coin_pb";
import { file_cosmos_proto_cosmos } from "../../../../cosmos_proto/cosmos_pb";
import { file_gogoproto_gogo } from "../../../../gogoproto/gogo_pb";
import type { Duration, Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_duration, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file sunrise/accounts/self_delegatable_lockup/v1/lockup.proto.
 */
export const file_sunrise_accounts_self_delegatable_lockup_v1_lockup: GenFile = /*@__PURE__*/
  fileDesc("CjhzdW5yaXNlL2FjY291bnRzL3NlbGZfZGVsZWdhdGFibGVfbG9ja3VwL3YxL2xvY2t1cC5wcm90bxIrc3VucmlzZS5hY2NvdW50cy5zZWxmX2RlbGVnYXRhYmxlX2xvY2t1cC52MSK1AQoGUGVyaW9kEjgKBmxlbmd0aBgBIAEoCzIZLmdvb2dsZS5wcm90b2J1Zi5EdXJhdGlvbkINyN4fAJjfHwGo57AqARJxCgZhbW91bnQYAiADKAsyGS5jb3Ntb3MuYmFzZS52MWJldGExLkNvaW5CRsjeHwCq3x8oZ2l0aHViLmNvbS9jb3Ntb3MvY29zbW9zLXNkay90eXBlcy5Db2luc5rnsCoMbGVnYWN5X2NvaW5zqOewKgEiYAoQVW5ib25kaW5nRW50cmllcxJMCgdlbnRyaWVzGAEgAygLMjsuc3VucmlzZS5hY2NvdW50cy5zZWxmX2RlbGVnYXRhYmxlX2xvY2t1cC52MS5VbmJvbmRpbmdFbnRyeSLaAQoOVW5ib25kaW5nRW50cnkSFwoPY3JlYXRpb25faGVpZ2h0GAEgASgDEjsKCGVuZF90aW1lGAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEINyN4fAJDfHwGo57AqARI0CgZhbW91bnQYAyABKAsyGS5jb3Ntb3MuYmFzZS52MWJldGExLkNvaW5CCcjeHwCo57AqARI8ChF2YWxpZGF0b3JfYWRkcmVzcxgEIAEoCUIh0rQtHWNvc21vcy5WYWxpZGF0b3JBZGRyZXNzU3RyaW5nQswCCi9jb20uc3VucmlzZS5hY2NvdW50cy5zZWxmX2RlbGVnYXRhYmxlX2xvY2t1cC52MUILTG9ja3VwUHJvdG9QAVpFZ2l0aHViLmNvbS9zdW5yaXNlbGF5ZXIvc3VucmlzZS94L2FjY291bnRzL3NlbGZfZGVsZWdhdGFibGVfbG9ja3VwL3YxogIDU0FTqgIpU3VucmlzZS5BY2NvdW50cy5TZWxmRGVsZWdhdGFibGVMb2NrdXAuVjHKAilTdW5yaXNlXEFjY291bnRzXFNlbGZEZWxlZ2F0YWJsZUxvY2t1cFxWMeICNVN1bnJpc2VcQWNjb3VudHNcU2VsZkRlbGVnYXRhYmxlTG9ja3VwXFYxXEdQQk1ldGFkYXRh6gIsU3VucmlzZTo6QWNjb3VudHM6OlNlbGZEZWxlZ2F0YWJsZUxvY2t1cDo6VjFiBnByb3RvMw", [file_amino_amino, file_cosmos_base_v1beta1_coin, file_cosmos_proto_cosmos, file_gogoproto_gogo, file_google_protobuf_duration, file_google_protobuf_timestamp]);

/**
 * Period defines a length of time and amount of coins that will be lock.
 *
 * @generated from message sunrise.accounts.self_delegatable_lockup.v1.Period
 */
export type Period = Message<"sunrise.accounts.self_delegatable_lockup.v1.Period"> & {
  /**
   * Period duration
   *
   * @generated from field: google.protobuf.Duration length = 1;
   */
  length?: Duration;

  /**
   * @generated from field: repeated cosmos.base.v1beta1.Coin amount = 2;
   */
  amount: Coin[];
};

/**
 * Describes the message sunrise.accounts.self_delegatable_lockup.v1.Period.
 * Use `create(PeriodSchema)` to create a new message.
 */
export const PeriodSchema: GenMessage<Period> = /*@__PURE__*/
  messageDesc(file_sunrise_accounts_self_delegatable_lockup_v1_lockup, 0);

/**
 * @generated from message sunrise.accounts.self_delegatable_lockup.v1.UnbondingEntries
 */
export type UnbondingEntries = Message<"sunrise.accounts.self_delegatable_lockup.v1.UnbondingEntries"> & {
  /**
   * @generated from field: repeated sunrise.accounts.self_delegatable_lockup.v1.UnbondingEntry entries = 1;
   */
  entries: UnbondingEntry[];
};

/**
 * Describes the message sunrise.accounts.self_delegatable_lockup.v1.UnbondingEntries.
 * Use `create(UnbondingEntriesSchema)` to create a new message.
 */
export const UnbondingEntriesSchema: GenMessage<UnbondingEntries> = /*@__PURE__*/
  messageDesc(file_sunrise_accounts_self_delegatable_lockup_v1_lockup, 1);

/**
 * UnbondingEntry defines an entry tracking the lockup account unbonding operation.
 *
 * @generated from message sunrise.accounts.self_delegatable_lockup.v1.UnbondingEntry
 */
export type UnbondingEntry = Message<"sunrise.accounts.self_delegatable_lockup.v1.UnbondingEntry"> & {
  /**
   * @generated from field: int64 creation_height = 1;
   */
  creationHeight: bigint;

  /**
   * end time of entry
   *
   * @generated from field: google.protobuf.Timestamp end_time = 2;
   */
  endTime?: Timestamp;

  /**
   * unbond amount
   *
   * @generated from field: cosmos.base.v1beta1.Coin amount = 3;
   */
  amount?: Coin;

  /**
   * validator address
   *
   * @generated from field: string validator_address = 4;
   */
  validatorAddress: string;
};

/**
 * Describes the message sunrise.accounts.self_delegatable_lockup.v1.UnbondingEntry.
 * Use `create(UnbondingEntrySchema)` to create a new message.
 */
export const UnbondingEntrySchema: GenMessage<UnbondingEntry> = /*@__PURE__*/
  messageDesc(file_sunrise_accounts_self_delegatable_lockup_v1_lockup, 2);

